### ISSUE TITLE
Créer un poster - contenus de présentation de l'ouvroir

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#100]
- [ ] pour la conférence Humanistica
- [x] prévoir une déclinaison en GIF animé pour le C3N

**Comment by emchateau** [comment]
Attention avant de procéder pour le GIF, j'ai l’impression qu‘ils ont prévu Powerpoint et Vidéo. Leur demander comment ils vont faire le montage.

**Comment by emchateau** [comment]
Il me semble que tout est terminé.

**Comment by lenaMK** [comment]
@emchateau as-tu soumi le contenu au wiki du c3n?

**Comment by emchateau** [comment]
C’est une autre issue
