### ISSUE TITLE
Commandes Maximo (Clefs)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#103]
- [x] 3 copies de la clef n°22 (Emmanuel + Josée)
- [x] 1 copie de la clef n° 105 (pour Emmanuel)
- [ ] remplacer la porte du C-8132 par une porte au sous-sol et faire poser une serrure à code dessus
- [x] 1 copie de la clef C-8132-3 (placard)
- [x] 1 copie de la clef C-8134-? (peut-être C-8134-1, n° de porte à valider par le serrurier) (placard)

Pour l'instant: 
- la clef du C-8132 sert pour ouvrir la salle d'ordinateurs, on verra plus tard si on veut faire poser une serrure à code dessus
- on laissera les clefs des placards dans le meuble à tiroir partagé

**Comment by lenaMK** [comment]
clefs du bureau: 

**C-8130** (D705 Litt et langue du monde). Josée et moi avons déjà une copie chacune. Il reste à obtenir quatre (4) copies pour Emmanuel, Kristine, Michael et la coordinatrice du CRIHN.

**C-8130-1** (D706 Etu Anglaise). Porte entre le bureau et la salle de conférence. Combien de copies? Juste une à laisser dans le bureau? On peut toujours ouvrir du bureau vers la salle de conférence...

@emchateau: au vu de la réponse de Blouin, qui dit qu'il faut changer les barillets si on ne veut pas avoir des clefs différentes pour le bureau, Kristine propose de conserver la situation actuelle car nous n'auront pas souvent besoin de la clef qui ouvre la porte entre le bureau et la salle de conférence (uniquement quand les personnes de l'entretien ferment à clef). Nous pourions donc mettr cette clef avec les autres (celles des placards) dans le petit meuble en bois partagé. 

Proposition: décider jeudi, nous commandons déjà les autres clefs (placards, petites clefs pour les meubles à tiroir) en attendant

**Comment by DanielRicher** [comment]
Demandes envoyées sur Maximo. 
Numéros de demande : 
DS-339502
DS-339505
DS-339506

**Comment by DanielRicher** [comment]
Suite à la réception des clés, l'une d'entre elle, la C-8132-3, ne correspond pas à la serrure en question. Également, nous avons constaté que la serrure du classeur en bois, correspondant à la clé n° 22, n'est pas fonctionnelle. 

Une demande Maximo a donc été envoyée afin de corriger la clé de porte, et de demander à remplacer la serrure du classeur.

Numéro de la nouvelle demande Maximo : DS-341494
Date de la demande : 21/06/2022

**Comment by emchateau** [comment]
Salut,
Je valide pour les clefs.
D’accord également avec Kristine sur le fait que nous pouvons conserver la situation en l’état.
Tu peux procéder aux commandes.
Bonne journée.

Emmanuel Château-Dutier
Professeur adjoint
