### ISSUE TITLE
Commandes Maximo (travaux)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#105]
- [ ] appeler pour voir s'ils ont une porte. S'il n'y a pas de porte, sinon échanger les portes C-8132 et C-8134-2 en attendant
- [x] #115
- [ ] #116
- [ ] devis contremaître 

- reconfiguration et installation d'une porte coulissante
- retirer la porte C-81
- peinture murs verts
-

**Comment by lenaMK** [comment]
@emchateau faudrait-il prévenir Michael pour qu'il prévienne le CELCP à propos du changement de porte + serrure prévu?

**Comment by emchateau** [comment]
Non, je lui en ai déjà fait part. Pour le reste, le temps que la porte soit là on aura le temps d’aviser le CELCP. Ou même, ils seront déjà partis.

**Comment by lenaMK** [comment]
Téléphone avec Patrice Hébert (contremaître) : il va faire la demande et chercher une porte qui correspond . Installation possible: environ mi-juin. On ne pourra pas faire la serrure en même temps, il va rappeler pour confirmer, commander la serrure à ce moment

**Comment by emchateau** [comment]
Excellent

Emmanuel Château
Professeur adjoint
Université de Montréal
@emchateau


Le 25 mai 2022 à 10:10, Lena Krause ***@***.***> a écrit :

﻿

Téléphone avec Patrice Hébert (contremaître) : il va faire la demande et chercher une porte qui correspond . Installation possible: environ mi-juin. On ne pourra pas faire la serrure en même temps, il va rappeler pour confirmer, commander la serrure à ce moment

**Comment by lenaMK** [comment]
Note (réponse des TI pour les prises réseaux) 
> Malheureusement, il est impossible d'activer les prises débutant par CH-XXX.
> Il est possible d'activer les prises C9-xxx mais dans ce cas-ci, elle sont toutes déjà activées.

Si on veut ajouter des prises, ce sera donc payant. En veut-on?

**Comment by DanielRicher** [comment]
Un courriel à été envoyé à Patrice, indiquant, d'une part, que nous avions trouvé une porte coulissante. D'autre part, j'ai aussi mentionné que l'installation se fera par le fournisseur, mais que nous aurons besoin de lui afin de démolir le mur en gypse. J'ai également indiqué qu'il fallait tailler une fente afin d'insérer la porte dans le local C-8134. Également, j'ai demandé qu'il poursuive ses recherches pour la vitre qui remplacera la porte C-8132-1. Nous effectuerons des recherches de notre côté également. Enfin, j'ai demandé des nouvelles pour la porte à C-8132, qui est è changer. 

Dans un soucis de respecter le budget fixé, j'ai demandé à Patrice une estimation des coûts pour l'ensemble de ces travaux.

**Comment by lenaMK** [comment]
le issue est trop générique, se fier aux issues plus précis
