### ISSUE TITLE
Rechercher des exemples de documents organisationnels

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#113]

**Comment by DanielRicher** [comment]
Documents trouvés : 

GEGD. Guide d’identification des documents essentiels, mai 2017, 30 p. [Document PDF]. [https://www.banq.qc.ca/dotAsset/4bf8f0d4-0157-40f7-b4ed-7978b79c336d.pdf](url) (Consulté le 27 mai 2022).

GAGNON-ARGUIN, Louise., Sabine MAS., & Dominique MAUREL. Les Genres De Documents Dans Les Organisations : Analyse Théorique Et Pratique, [Livre numérique], Québec, QC, Presses de l'Université du Québec, 2015, format PDF.[https://bibliopiaf.ebsi.umontreal.ca/bibliographie/GFT4W93A/download/LJBYY38Z/Gagnon-Arguin%20et%20al.%20-%202015%20-%20Les%20genres%20de%20documents%20dans%20les%20organisations%20ana.pdf](url) (Consulté le 27 mai 2022).

«Structure organisationnelle», Entreprises Québec, [En ligne], le 14 juillet 2021. [https://www2.gouv.qc.ca/portail/quebec/ressourcesh?lang=fr&g=ressourcesh&sg=personnel&t=s&e=2074413809:464905121:1020760869:1226594936](url) (Consulté le 27 mai 2022).

**Comment by DanielRicher** [comment]
-Documents trop exhaustifs, et donc, peut-être moins appropriés pour notre type d'organisation. Voir à simplifier le protocole et l'adapter aux besoins réels du laboratoire.
-Demander à Emmanuel et Lena de fournir les informations essentielles pour le document.
