### ISSUE TITLE
travaux peinture C-8130

### ISSUE THREAD

**Issue by ghost** [ouvroir/labouvroir#115]

**Comment by DanielRicher** [comment]
Demande envoyé. Numéro de demande : DS-339240

**Comment by DanielRicher** [comment]
Suite à notre rencontre avec le contremaître, une nouvelle demande de devis a été envoyée sur Maximo.

**Comment by DanielRicher** [comment]
Numéro de demande : DS-339491

**Comment by DanielRicher** [comment]
Nouvelle demande envoyée à Martin pour le local C-8130

Numéro de demande : DS-340048

**Comment by DanielRicher** [comment]
Travaux en cours. Yasser, le peintre, m'a confirmé  qu'il aura terminé à la fin de la semaine, soit le 9 ou 10 juin 2022. La peinture à tableau blanc a été commandée par eux, et donc, nul besoin de le faire de notre côté. L'équipe de peinture ont aussi communiqué avec l'équipe des planchers afin de coordonner les travaux.

**Comment by lenaMK** [comment]
Nous devons commander la peinture nous même

- [ ] commander/acheter de la peinture tableau blanc
- [ ] confirmer la réception à Georges Apreutesei

**Comment by lenaMK** [comment]
Le Québec au complet semble en rupture de stock de peinture tableau blanc. 
@emchateau les options: 
- acheter/récupérer un tableau blanc normal
- [panneau mural](https://www.renodepot.com/fr/panneau-mural-tableau-blanc-resistant-a-lhumidite-blanc-lustre-4-pi-l-x-8-pi-l-x-1-8-po-e-g6121904480-50685049) (comment l'installer?)
- [panneaux amovibles](https://www.rona.ca/fr/produit/grand-tableau-wallpops-en-vinyle-autocollant-effacable-a-sec-blanc-wpe0446-330010321)
- attendre (notification par courriel quand il y aura à nouveau de la peinture tableau blanc

**Comment by emchateau** [comment]
Les tableaux blancs sont très chers et moche.
J’attendrais plutôt. Ils vont bien en recevoir à un moment ou un autre.

Envoyé de mon iPhone

Le 14 juil. 2022 à 16:22, Lena Krause ***@***.***> a écrit :

﻿

Le Québec au complet semble en rupture de stock de peinture tableau blanc.
@emchateau<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femchateau&data=05%7C01%7Cemmanuel.chateau.dutier%40umontreal.ca%7C6c608f936e7a4f66b81108da65a4564f%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637934053741330433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YqgAbXuT9gSE02S3zk1lacQ4ekHKOVF1gwxlGB7dnzA%3D&reserved=0> les options:

  *   acheter/récupérer un tableau blanc normal
  *   panneau mural<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.renodepot.com%2Ffr%2Fpanneau-mural-tableau-blanc-resistant-a-lhumidite-blanc-lustre-4-pi-l-x-8-pi-l-x-1-8-po-e-g6121904480-50685049&data=05%7C01%7Cemmanuel.chateau.dutier%40umontreal.ca%7C6c608f936e7a4f66b81108da65a4564f%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637934053741330433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3Mne6dEeP9xa47QX39IpLfXX9Fh0QQPiea4WQS8rCRE%3D&reserved=0> (comment l'installer?)
  *   panneaux amovibles<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rona.ca%2Ffr%2Fproduit%2Fgrand-tableau-wallpops-en-vinyle-autocollant-effacable-a-sec-blanc-wpe0446-330010321&data=05%7C01%7Cemmanuel.chateau.dutier%40umontreal.ca%7C6c608f936e7a4f66b81108da65a4564f%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637934053741330433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s6SgdNAbvfuw0Ut%2BCQYG%2FM8k%2BykVf3p0%2FqfgSBatqF4%3D&reserved=0>
  *   attendre (notification par courriel quand il y aura à nouveau de la peinture tableau blanc

**Comment by lenaMK** [comment]
on ouvrira une autre issue quand il y aura de la peinture disponible
