### ISSUE TITLE
Recherche et installation de la porte coulissante

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#118]
- [Porte de grange en métal en verre claire](https://www.homedepot.ca/produit/colonial-elegance-porte-de-grange-en-metal-en-verre-claire-nation-avec-ensemble-de-quincaillerie-d-installation/1001593960) 571$, 84x37
- [Porte de grange préfinie en verre Glacier de Colonial Elegance](https://www.renodepot.com/fr/porte-de-grange-prefinie-en-verre-glacier-de-colonial-elegance-avec-trousse-dinstallation-33-po-x-84-po-verre-givre-kmglgcf-33bn-330754335?catalogId=10551&langId=-2&storeId=10701&ddkey=https%3ARenoChangeSelectedStoreCmd) 699$, 32x80
- [Colonial elegance](https://www.colonialelegance.com):  large 42'

**Comment by lenaMK** [comment]
explorer l'idée de portes de patio

**Comment by DanielRicher** [comment]
Fournisseurs contactés pour informations sur les portes patio : 
-Toutes les options comportent une bordure inférieure avec rail d'une hauteur d'environ 2". Impossible de faire sans. 
-Tous les délais de livraison sont estimés à l'automne 2022.

-Portes et fenêtres Verdun : Informations de la réceptionniste : 
   -Modèle "Loft", cadrage noir.
   -Un représentant a tenté de téléphoner Lena, sans succès. Il faudrait donc rappeler. 
   -Aucune information fournie pour le moment. Il faut attendre de parler au représentant.
Page web : [https://portesetfenetresverdun.com/fr/porte/patio-loft/](url)


-Fentek : Informations du représentant : 
   -Modèle "Loft" ou "Hybride", cadrage noir.
   -Porte patio standard, (LxH), 71,5" x 81".
   -Possibilité d'ajouter une fenêtre au-dessus pour combler l'espace en hauteur.
   -Aluminium : 5000$.
   -PVC ou Hybride : entre 3000$ et 4000$.
   -Frais d'installation : entre 1000$ et 1500$.
   -Délai de livraison : 4 à 5 mois.
   -Un représentant devrait envoyer un devis par courriel à Lena au courant de la semaine (d'ici demain, 1er juin 2022).
Page web : [https://www.fentek.ca/portes-patio](url)


-Fenêtre Magistral : informations du représentant :
   -Le représentant enverra un devis avec les différentes options de modèle, cadrage noir.
   -Porte patio, (LxH), 58,5" x 81".
   -Différentiel de verre permettant une meilleur insonorisation (peut-être pas nécessaire).
   -Prix porte patio, livraison et installation : entre 7000$ et 8000$.
   -Un représentant devrait envoyer un devis par courriel à Lena au courant de la semaine (d'ici jeudi, 2 juin 2022).
   -Délai de livraison : novembre 2022.
Page web : https://www.fenetresmagistral.com/cat/portes/porte-patio/

**Comment by lenaMK** [comment]
Soumission Kadrium sésame

Jenna
- [ ] rabais FCI
- [ ] rideau (fils insonorisants)
- [ ] poignées: demander les options et les prix (+éventuelles recommandations)
- [ ] rdv en juin, repréciser la date + venir avec le nuancier pour les couleurs (jeudi tôt le matin ou en après-midi de préférence)


- [ ] se renseigner auprès de Jessica pour les moyens de paiement

**Comment by DanielRicher** [comment]
Questions d'Emmanuel à poser à l'installateur de Kadrium Sésame (Interfonction) et à Patrice, le contre-maître, lors de la prise de mesure (21 juin 2022, date à confirmer) : 

- Possibilité d'avancer la porte (ouverture) vers la salle de conférence afin de l'aligner avec le reste du mur (éliminer le décalage)
- Valider le système de soutien au plafond (poutre ?), puisque clouer au plafond de béton semble peut-être complexe.
- Évaluer le positionnement de la fente dans le local C-8134, puisque la porte sera décalée, c'est-à-dire avancée vers la salle de conférence (assez d'espace restante pour la porte).

**Comment by lenaMK** [comment]
Georges, le contremaître, a fait suivre notre demande à Marc Desbois (Préventionniste en incendie, Direction de la prévention et de la sécurité (DPS)) pour valider la sécurité des travaux: 
- remplacer la porte C-8132-1 par une vitre
- changer la porte C-8132-2 par une porte coulissante

**Comment by lenaMK** [comment]
Marc Desbois est en train de traiter le dossier, il devrait nous fournir une réponse la semaine prochaine

**Comment by lenaMK** [comment]
validation par Marc Desbois 
> Du coté prévention incendie nous n'avons pas d'objection pour c'est travaux.

**Comment by lenaMK** [comment]
relance auprès de M. Apreutesei (contremaître) faite le 23 août

**Comment by lenaMK** [comment]
changement de contremaître le 12 septembre. M. Apreutesei ne veut pas "commencer" le chantier de la porte coulissante puisqu'il ne pourra pas le terminer

**Comment by lenaMK** [comment]
Nous avons rencontré le contremaître et les installateurs jeudi passé pour évaluer les options et prendre note du fonctionnement (il faut avoir fait le travail préalable avec le menuisier à l'UdeM, pour que les installateurs reviennent et prennent les mesures définitives, ce qui permet de lancer la commande. Ensuite, délai de 6 à 8 semaines, puis installation).
J'ai reçu l'information sur un vitrier qui pourrait faire une cloison et une porte en verre. Toutefois la porte ne serait pas coulissante. J'ai reparlé avec le contremaître pour le devis du menuiser ( pour le plan A: porte coulissante, qui requiert de renforcer la structure actuelle pour y déposer le mécanisme de la porte coulissante): il devrait avoir les informations nécessaires pour nous revenir avec ça

**Comment by lenaMK** [comment]
changement de plan, je vais ouvrir une nouvelle issue pour la cloison et porte vitrée
