### ISSUE TITLE
Décapage et cirage des planchers 

### ISSUE THREAD

**Issue by DanielRicher** [ouvroir/labouvroir#119]
Une première demande de devis a été envoyée sur Maximo afin d'effectuer le décapage et le cirage de la totalité des planchers dans nos locaux. (C-8130, C-8132 et C-8134). 
Numéro de demande : DS-339495.

**Comment by lenaMK** [comment]
Simon Trudeau viendra demain pour voir le local et l'état des planchers

**Comment by DanielRicher** [comment]
Nouvelle demande envoyée à Martin pour le local C-8130

Numéro de demande : DS-340048

**Comment by DanielRicher** [comment]
L'équipe de peinture a communiqué avec celle des planchers afin de coordonner le travail. On m'a confirmé que le récurage et cirage du plancher au C-8130 sera terminé d'ici lundi 13 ou mardi 14 juin 2022. Cependant, je confirmerai l'information de nouveau en cours de semaine.

**Comment by lenaMK** [comment]
fait
