### ISSUE TITLE
Propositions palettes de couleur pour la peinture du C-8132 et C8132-2

### ISSUE THREAD

**Issue by ghost** [ouvroir/labouvroir#125]
Déterminer 3 options de palette afin de les proposer à Johanne Lamoureux, et ainsi, orienter nos choix de couleur pour le local C-8132 (entrée) et C-8132-2 (Salle de conférence).

**Comment by lenaMK** [comment]
- option d'une section (murs opposés dans la salle de conférence par exemple) anthracite le reste blanc

**Comment by lenaMK** [comment]
@emchateau des nouvelles de Johanne pour la peinture?

**Comment by emchateau** [comment]
Mail fait

**Comment by emchateau** [comment]
Nous avons le go de Johanne qui parle cependant des autres couleurs. J'ai l'opportunité de la rencontrer lundi, je propose d'essayer de lui présenter les pistes de mobilier pour le local.

**Pour la peinture de ce mur, ne rien faire avant d'avoir garanti que la salle reste utilisable (support mobile pour écran ou pose d'un nouvel écran).**

@lenaMK il y a plusieurs modèles de support d'écran. Il faudrait regarder ce qu'avait prévu INSO. Nous pouvons peut-être nous permettre une solution plus légère et moins coûteuse et sans doute moins encombrante comme l'écran sera plus petit.

**Comment by lenaMK** [comment]
- [ ] code couleur (selon le nuancier: à confirmer si c'est bien SICO de chez RONA)  pour le gris anthracite (bateau à vapeur?)
- [ ] commander le support pour l'écran avant la peinture

**Comment by lenaMK** [comment]
@emchateau  confirmation du code couleur: https://www.sico.ca/fr-ca/nos-couleurs/palette-de-couleurs-sico/les-neutres (soit dans les neutres, soit dans le bleu j'imagine) 
Il suffit de choisir la couleur et le contremaître fera la commande, il peut nous trouver des peintres dans un délai rapide

**Comment by lenaMK** [comment]
- [pluton](https://www.sico.ca/fr-ca/nos-couleurs/palette-de-couleurs-sico/bleu/pluton) bleus
- [aura de minuit](https://www.sico.ca/fr-ca/nos-couleurs/palette-de-couleurs-sico/bleu/aura-de-minuit) bleus
- [étoilé](https://www.sico.ca/fr-ca/nos-couleurs/palette-de-couleurs-sico/bleu/etoile) bleus
- [eaux abyssales](https://www.sico.ca/fr-ca/nos-couleurs/palette-de-couleurs-sico/turquoise/eaux-abyssales) turquoises
- [noir d'ange](https://www.sico.ca/fr-ca/nos-couleurs/palette-de-couleurs-sico/violet/noir-d-ange) violets
- [élite aristocrate](https://www.sico.ca/fr-ca/nos-couleurs/palette-de-couleurs-sico/violet/elite-aristocrate) violets (non mais quel nom!)

**Comment by ktanton-work** [comment]
N'attendons-nous pas encore la préférence de couleur de Johanne ? Pour mes préférences (qui ne sont pas gravées dans la pierre), j'aime l'Esquisse pour une couleur neutre et pour une couleur d'accent plus sombre, j'aime Pluton ou Etoile. Les différences sont subtiles, donc s'il y a une autre combinaison que le groupe préfère, c'est d'accord.

**Comment by lenaMK** [comment]
De ce que j'ai compris, Johanne a dit ok pour un gris anthracite et le reste de la salle en blanc (vu que le bureau est blanc). Si c'est bien ça, alors il reste à choisir le gris anthracite, d'où la sélection ci-dessus

**Comment by lenaMK** [comment]
pluton :)

**Comment by ktanton-work** [comment]
Okay. Donc, le blanc me va très bien, et mes deux choix sont pluton ou étoilé.

Merci,
Kristine’

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d’histoire de l’art et d’études cinématographiques
514 343-2194

On Aug 31, 2022, at 11:14 AM, Lena Krause ***@***.******@***.***>> wrote:



De ce que j'ai compris, Johanne a dit ok pour un gris anthracite et le reste de la salle en blanc (vu que le bureau est blanc). Si c'est bien ça, alors il reste à choisir le gris anthracite, d'où la sélection ci-dessus

**Comment by lenaMK** [comment]
transférée à l'issue #181
