### ISSUE TITLE
Emménagement dans le local (UdeM interne)

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#13]
L’emménagement dans le local ne sera possible qu’à compter de septembre.
En attendant, héberger le personnel technique dans nos bureaux personnels s’il est déjà recruté.

**Comment by lenaMK** [comment]
- [ ]  mesures et marquage des prises
- [ ] plaque
- [ ] clefs (passe)
- [ ] test des prises existantes
- [ ] devis pour les travaux (contremaître)
- [ ] devis serrurier pour sécurisation
- [ ] sélection d'agences de mobilier
- [ ] envoi des plans aux agences
- [ ] commande du gros matériel
- [ ] choix et commande du mobilier

**Comment by lenaMK** [comment]
aller voir la plaque du labo ciné.média (andré gaudreau)
