### ISSUE TITLE
Confirmer dates événements Ouvroir 2022-2023

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#133]
courriel envoyé à Michael

**Comment by lenaMK** [comment]
@emchateau valider l'horaire de réunion avec Marcello
@ktanton-work voir les disponibilités de Katherine Cook et l'anthropolab

**Comment by lenaMK** [comment]
## Dates (mardi midi ou après-midi)
### session d'automne
- 13 septembre: portes ouvertes
- 27 septembre
- 11 octobre
~~25 octobre~~: mi-session du 24 au 30 octobre 2022
- 1 novembre
- 15 novembre: Emmanuel est en Europe
- 29 novembre
- 13 décembre

### session d'hiver 
- 10 janvier
- 24 janvier
- 7 février
- 21 février
~~28 février~~ mi-session: du lundi 27 février au dimanche 5 mars 2023
- 8 mars
- 22 mars
- 4 avril
- 18 avril
 
Activité avec anthropo et photogrammétrie → hiver 2023

**Comment by lenaMK** [comment]
pour un midi-causerie sur Righettino, ce serait le 27 septembre en ce cas @emchateau

**Comment by ktanton-work** [comment]
Je suis toujours en train de planifier mon voyage de recherche d'automne, mais je ne serai probablement pas disponible du 24 octobre au 15 novembre. Je vous tiens au courant.

**Comment by lenaMK** [comment]
viser un atlier IIIF Atkins le 29 novembre, à suivre

**Comment by emchateau** [comment]
Denis a validé le 27 septembre pour le midi-causerie.
Pour l’atelier IIIF, attendre négociation avec la bib. Fermer l’issue et ouvrir de nouvelles tâches pour ce qui reste en suspends ?
Discuter lors de notre prochaine réunion l’envoi d’un calendrier.

**Comment by lenaMK** [comment]
@emchateau dates possibles pour Antoine Courtin: 
- 11 octobre
- 8 novembre
- 29 novembre
- 6 ou 13 décembre

**Comment by emchateau** [comment]
Antoine est Ok pour un format léger. Je lui ai proposé le mode discussion et communiqué les dates.
PS: plutôt que d’avoir une issue qui ne se ferme jamais, ne devrions-nous pas plutôt privilégier des issues séparées ?
