### ISSUE TITLE
Planifier une journée portes ouvertes (13 septembre)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#134]
- [x] événement calendrier
- [x] premier jets idées pour la journée
- [x] liste du matériel et aménagement souhaité

**Comment by lenaMK** [comment]
Au programme tout au long de la journée:
- présentation du laboratoire et des locaux partagé avec le CRIHN depuis la fin du printemps passé
- démonstrations de projets et d'équipement
- rencontre avec les membres de l'équipe
- café, thé et pâtisseries (apportez vos tasses réutilisables)

Démonstration de projets et d'équipement pendant la journée portes ouvertes (13 septembre):

    démo Righettino (figma @KenanOudin et prototype @WilliamDiakite)
    démo modèle 3D Mauricio (sur le grand Mac) ?
    @ktanton-work bases des données et montrer un modèle en 3D.
    demander à Talitha si elle peut présenter son travail @emchateau
    je peux présenter mon atlas ou MONA ou autre
    scanTents (1 monté, pour permettre de le tester)

Est-ce qu'on demande à Josée ou quelqu'un d'autre de présenter CIÉCO?
Si on présente CIÉCO, présenter le CRIHN aussi (demander à Michael ou un·e de ses étudiant·e·s)

prévoir un poste sur lequel les gens peuvent s'inscrire à notre liste d'information et consulter notre site web

**Comment by lenaMK** [comment]
- [ ] demander un projecteur au département

**Comment by emchateau** [comment]
Super, ajouter ANR experts (emmanuel)
Prévoir un projecteur (département)

**Comment by lenaMK** [comment]
tu seras pas là en fait

**Comment by lenaMK** [comment]
- [ ] : étiquettes
- [ ] : feuilles A2 ou A3 pour lister les projets (1 par table)

**Comment by emchateau** [comment]
experts
Application de dépouillement de sources archivistiques et de création de prosopographie
Emmanuel Chateau-Dutier et Josselin Morvan (conception et développements numériques)

Righettino
Faire parler une image de la Renaissance à l’ère du numérique (prototype d’exposition interactive).
William Diakité, Chaitanya Tekane (développeurs), Kenan Oudin (design éditorial et médiation numérique), Emmanuel Chateau-Dutier et Denis Ribouillault (direction scientifique)
