### ISSUE TITLE
Décision concernant l'offre de consultation - Koumbit

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#135]
> J'avais préparé une ébauche de devis, mais je n'étais vraiment pas sûr de sa validité. L'infrastructure que vous souhaitez mettre en place à long terme est assez grosse et complexe. Puis, elle sort aussi de nos habitudes et des domaines que nous maitrisons mieux (hors de notre infrastructure, openstack et nodes web que nous connaissons moins), de tel sorte qu'il reste beaucoup d'inconnus avec lesquelles jongler pour produire un devis fiable et précis. J'ai consulté un de mes collègues plus expérimenté lors de son retour de vacance et il m'a conseillé quelque chose qui me parrait beaucoup plus pertinent.
> Plutôt que de vous fournir un devis sans trop être certain d'où je m'en vais et de risquer de mauvaises surprises (p.ex.: dépassement des heures prévues, incapacité à accomplir certaines tâches, voire fin de contrat si on n'est pas en mesure de mener le projet à terme), le mieux serait de nous entendre sur une banque d'heures dédiées à l'analyse préliminaire du projet. On pourrait penser à 15 heures de consultation.
> Cette banque d'heures nous permettrait d'explorer openstack pour connaitre un peu mieux ce qui ce qu'il permet. Une des grosses questions qui rend le devis difficile à produire pour le moment est de savoir comment nous allons planifier le réseaux et comment les différents serveurs pourront communiquer entre eux et être accessibles depuis l'extérieur, en sachant que vous aurez un nombre d'IP publiques très limité. Comme piste préliminaire, il faudrait voir si openstack permet de d'implémenter des VLAN (réseaux privés), sinon il y aurait l'idée de mettre en place un VPN ou d'utliser Nginx pour faire un reverse proxy (deux choses qui sont un peu nouvelles pour nous). Pour nodeJS, nos outils actuels ne font qu'installer la version disponible dans les dépôts Debian, alors que vous aurez probablement besoin de versions plus récentes. Il faudra réfléchir à comment mettre ça en place (et quoi mettre en place exactement). Enfin, la question des bases de données soulève au
 ssi plusieurs intérrogations, nommément, combien de services sur combien de serveurs devrons-nous mettre en place. Enfin, le tout devra être réfléchi dans une optique à plus long terme afin de prévoir l'accroissement de l'infrastructure.
> L'idée ici est de pouvoir réfléchir plus longuement sur les questions tout en pouvant mettre la main à la pâte en commençant à utiliser votre compte openstack (ça implique donc qu'on devra avoir les accès pour produire l'analyse). Comme il s'agit pour l'instant d'une analyse qui pourrait aboutir au constat que c'est trop gros pour nous (espérons que non) ou à produire un devis qui ne vous convient pas, cette banque d'heures nous permettra de produire un rapport qui vous sera utile même si Koumbit en vient à ne plus être dans l'équation une fois qu'on aura produit un devis complet. Selon comment les choses se dessinent durant l'analyse, cette banque d'heure pourrait aussi permettre de faire les premiers pas pour mettre des choses en place en vu d'entamer le vrai travail.
> Pour finir, avec de gros changements dans la composition de notre équipe, je crois qu'il serait plus réaliste de planifier la mise en place de la première phase pour le mois d'octobre plutôt que la fin de l'été. Pour l'analyse, si vous êtes d'accord pour aller de l'avant avec l'idée de banque d'heures, le rapport pourrait être produit pour le début du mois de septembre.

**Comment by ktanton-work** [comment]
Je voudrais juste clarifier que ce courriel était une mise à jour de notre position sur les serveurs.

Amicalement,
Kristine

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d'histoire de l'art et d'études cinématographiques
514 343-2194

On Jul 14, 2022, at 4:34 PM, Lena Krause ***@***.******@***.***>> wrote:



Assigned #135<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fouvroir%2Flabouvroir%2Fissues%2F135&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C26db4bd1a18f4a12854408da65d83756%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637934276559700183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FyZJxFKt5iZQ75HziF0W5EuYOuwvmH%2F6g%2B46fucSTxo%3D&reserved=0> to @ktanton-work<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fktanton-work&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C26db4bd1a18f4a12854408da65d83756%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637934276559700183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VA0J38k8uMizFRC1igRovwG5%2BqEegYe5ZQ8mavCiPpo%3D&reserved=0>.

**Comment by emchateau** [comment]
Oui c’est une tâche à discuter

Emmanuel Château
Professeur agrégé
Université de Montréal
@emchateau


Le 15 juil. 2022 à 14:43, ktanton-work ***@***.***> a écrit :

﻿

Je voudrais juste clarifier que ce courriel était une mise à jour de notre position sur les serveurs.

Amicalement,
Kristine

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d'histoire de l'art et d'études cinématographiques
514 343-2194

On Jul 14, 2022, at 4:34 PM, Lena Krause ***@***.******@***.***>> wrote:



Assigned #135<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fouvroir%2Flabouvroir%2Fissues%2F135&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C26db4bd1a18f4a12854408da65d83756%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637934276559700183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FyZJxFKt5iZQ75HziF0W5EuYOuwvmH%2F6g%2B46fucSTxo%3D&reserved=0> to @ktanton-work<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fktanton-work&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C26db4bd1a18f4a12854408da65d83756%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637934276559700183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VA0J38k8uMizFRC1igRovwG5%2BqEegYe5ZQ8mavCiPpo%3D&reserved=0>.

**Comment by emchateau** [comment]
Suivi réunion de labo 26-07-2022
La réponse de Koumbit traduit une certaine surestimation de la complexité des besoins en même temps qu’un manque de connaissance sur les technologies ciblées. La solution proposées est raisonnable mais devrait plutôt déboucher sur un premier produit.
- demander à Calcul Québec la création d’une première instance
- prendre contact avec le sysadmin de la CRC sur les écritures numériques
- en fonction des réponses du sysadmin de la CRC, discuter avec Koumbit de leur proposition en ciblant un premier produit (ils n’étaient pas disponibles avant la rentrée)

**Comment by lenaMK** [comment]
réponse à Koumbit @emchateau

**Comment by emchateau** [comment]
Faite
