### ISSUE TITLE
demander les infos du système de conférence du carrefour

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#137]
besoins: 
- micro suspendu
- caméra directionnelle

**Comment by emchateau** [comment]
Réponse de Maxime 27 juillet

> Je n’ai pas la liste des équipements exacts qui ont été installés, car il y a eu beaucoup de restitution. La liste que j’ai est celle qu’ils devaient mettre mais rien n’a été respecté en raison des défauts d’approvisionnement. J’ai tenté à 4 reprises de me faire fournir cette dite liste finale, mais comme il y a eu 3 entrepreneurs impliqués dans ce dossier, tout le monde se renvoie la balle.
>  
> Par contre, je peux assurément te donner un feedback. En ce moment, c’est très tranquille au carrefour, donc je te propose de faire une visite sur place. Les salles sont libres et je travaille du lundi au jeudi. Il faudrait donc me dire quand tu serais disponible pour qu’on se donne RDV sur place. Tu pourrais prendre des photos et je crois que ce serait faisable de trouver les bons modèles avec la marque.
>  
> Est-ce que tu serais libre la semaine prochaine (sauf lundi)? Idéalement, il faudrait faire ceci avant le 12 août, car les activités reprennent abruptement ensuite.
> 

Nous pourrions proposer d’y aller mardi après notre réunion ? qu’en dis-tu @lenaMK ?

**Comment by lenaMK** [comment]
Oui c'est bon pour mardi

**Comment by emchateau** [comment]
Ok, j’ai écrit à Maxime pour lui demander ses disponibilités

Emmanuel Château-Dutier
Professeur agrégé

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by lenaMK** [comment]
[micro](https://clockaudio.com/products/suspended/c303w-rf)

**Comment by lenaMK** [comment]
[camera](https://www.minrraycam.com/uv950a-series-full-hd-ptz-camera.html) environ celle-ci, mais les specs sont moins bonnes (5x zoom, F1.8-2.8 f3.1mm-f15.5mm)
