### ISSUE TITLE
Sys admin - crcen

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#138]
- [x] obtenir le nom du sys-admin de la chaire
- [x] le contacter pour savoir quelles sont ses disponibilités pour une rencontre
- [x] lui demander quelles sont ses éventuelles disponibilités pour un contrat

**Comment by lenaMK** [comment]
J'ai demandé à Antoine sur le mattermost de la chaire mais il ne m'a toujours pas répondu

**Comment by emchateau** [comment]
Je viens de faire un mssg à Marcello pour lui demander de nous mettre en contact. Amitiés

**Comment by emchateau** [comment]
Échange avec Tim qui est de retour le

**Comment by emchateau** [comment]
Demande de rdv Tim pour vendredi 2 en apm
