### ISSUE TITLE
Choix des ordinateurs

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#139]
J'ai préparé un [comparateur des options et des coûts](https://docs.google.com/spreadsheets/d/1ShbI-JEIYuACUZkWTojnE9M7R3r0Qwkp/edit?usp=sharing&ouid=101314893057499854802&rtpof=true&sd=true) pour les ordinateurs (onglet Apple). 

Pourriez-vous svp me confirmer vos préférences pour 

- [ ] clavier (avec pavé numérique ou sans? touchID?)
- [ ] souris (normale ou trackpad)
- [ ] couleurs (blanc ou noir pour clavier/souris)
- [ ] specs pour le macStudio max
- [ ] specs pour le macStudio ultra

**Comment by emchateau** [comment]
Salut, sauf erreur : il faudrait partir du prix de base prévu dans l’item 9 :  16 240,00  (prix de liste),  14 764,00 prix FCI

**Comment by emchateau** [comment]
J’aurais tendance à votre pour l’option 4 : 
- M1 10 cœurs, processeur graphique 32 cœurs et neural engine 16 cœurs, upgrade 64Go, 2To
- M1 Ultra 20 cœurs, processeur graphique 64 cœurs et neural engine 32 cœurs, upgrade 128Go, 2To

**Comment by lenaMK** [comment]
choix complété
