### ISSUE TITLE
Choisir un horaire pour la clinique numérique (permanance Lena)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#141]
Je pense à un horaire de 2h hebodmadaire où je serai disponible (au labo et en zoom) pour aider les étudiant·e·s du partenariat et du département
Par exemple: mardi (après le fika) de 16h à 18h?

**Comment by ktanton-work** [comment]
Deux heures, c'est trop pour toi ? Serait-il accessible à tous les étudiant.es en histoire de l'art ?

**Comment by ktanton-work** [comment]
C'est quelque chose que je peux annoncer sur la page du tutorat.

**Comment by lenaMK** [comment]
mardi 16h à 18h :)
