### ISSUE TITLE
Soumission INSO (achats FCI)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#142]
Salut, 

voici ce qu'il reste à confirmer pour la demande de [soumission INSO](https://docs.google.com/spreadsheets/d/1N35S7dw5ynTWNE8iaa0gSJIZjK7P65E2BkL7WZJA3Fc/edit?usp=sharing): 

- [x] MacBook (désolée j'ai un trou de mémoire si je devais vérifier les prix des MacBook Air ou MacBook Pro pour les deux stations de travail restantes? Quel était le verdict @emchateau ou  @ktanton-work ?)
- [x] imprimante (@emchateau peux-tu me confirmer si c'est la même que la tienne ou m'envoyer les détails de la tienne svp) 
- [x] casques de VR (il me reste à vérifier les modèles disponibles, @ktanton-work si tu as des recommandations ou autre n'hésite pas)
- [x] iPad: est-ce qu'on garde les iPad 8e génération? la 9ème génération coûte 50$ de plus par iPad
- [x] ordinateur (pour l'écran: à part si on veut un appleTv? je vais faire des recherches à ce sujet) 
- [x] appareil photo (@emchateau tu voulais me transmettre d'autres modèles qui te semblaient plus performants pour nos besoins?) 
- [x] kit de vidéo-conférence (à détailler avec le micro et la caméra que nous avons identifiés au carrefour) 

Désolée ça fait beaucoup, on peut créer des issues au compte-goutte au besoin (hover par-dessus la tâche à droite et il y a l'option "transformer en issue)

**Comment by ktanton-work** [comment]
D'après notre discussion de mardi, le MacBook est meilleur car les MacBook Airs sont moins durables. Ils sont plus fragiles.
J'ai envoyé un courriel à quelques collègues qui utilisent la RV pour savoir s'ils avaient des recommandations spécifiques.

**Comment by emchateau** [comment]
+1

Emmanuel Château
Université de Montréal
@emchateau


Le 4 août 2022 à 18:22, ktanton-work ***@***.***> a écrit :

﻿

D'après notre discussion de mardi, le MacBook est meilleur car les MacBook Airs sont moins durables. Ils sont plus fragiles.
J'ai envoyé un courriel à quelques collègues qui utilisent la RV pour savoir s'ils avaient des recommandations spécifiques.

**Comment by ktanton-work** [comment]
Le technicien du laboratoire de VR à Dartmouth recommande ce qui suit :


  *   I think the reverb G2 is the best wired headset out right now
  *   Meta Quest 2 is the best standalone (i.e no wires) option if you’re looking for variety of software
  *   Pico Neo 3 is a good standalone option if you want to be free of Facebook’s ecosystem, but software is more limited than on Quest. The newer versions of this headset can also function as a wired headset and use steamVR.

Nick Camerlenghi suggère fortement que l’un des casques soit filaire, car cela nous permettrait d’utiliser des logiciels haut de gamme. Les puces des casques grand public ne sont pas encore capables de gérer une structure complexe, comme une cathédrale gothique. Une autre collègue qui utilise un modèle VR de Reims à des fins pédagogiques utilise l’Oculus Quest 2. Elle note cependant qu’il n’a que l’espace de stockage d’un iPhone, ce qui peut être un problème pour les rendus complexes. La vidéo à 360° fonctionne bien sur l’Oculus.

Tout cela étant dit, je pense que si nous pouvions avoir un Oculus (ou l’équivalent) et un casque VR filaire, nous pourrions faire des expériences.

Amicalement,
Kristine

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d’histoire de l’art et d’études cinématographiques
514 343-2194

On Aug 8, 2022, at 3:33 PM, Emmanuel Château-Dutier ***@***.******@***.***>> wrote:


+1

Emmanuel Château
Université de Montréal
@emchateau


Le 4 août 2022 à 18:22, ktanton-work ***@***.***> a écrit :

﻿

D'après notre discussion de mardi, le MacBook est meilleur car les MacBook Airs sont moins durables. Ils sont plus fragiles.
J'ai envoyé un courriel à quelques collègues qui utilisent la RV pour savoir s'ils avaient des recommandations spécifiques.

**Comment by emchateau** [comment]
Merci beaucoup @ktanton-work  pour ces informations.
Je pense que nous devons acheter un oculus quest ne serait ce que parcequ’il s’agit du matériel le plus populaire et pour lequel le plus d’applications sont développées pour les musées. 
@lenaMK peux-tu regarder les prix des différents matériels évoqués s’il te plaît ? Je vais écrire à l’étudiant de Marie qui travaille sur la VR wet les musées pour également recevoir son avis. Bernard Perron ne connaissait pas trop ce qu’il y avait en dehors de l’occulus quand nous en avons parlé ensemble au printemps. Je vais demander également à Carl ce qu’il en pense.
Amitiés,
Em

**Comment by emchateau** [comment]
Mail à Flavio fait

**Comment by lenaMK** [comment]
@emchateau

**Comment by lenaMK** [comment]
prix et recherche sur les casques VR: https://docs.google.com/spreadsheets/d/1ShbI-JEIYuACUZkWTojnE9M7R3r0Qwkp/edit#gid=1266373557

**Comment by ktanton-work** [comment]
Si je me souviens bien, Emmanuel pensait qu’il fallait s’en tenir à un casque sans fil, car il est plus pertinent pour les besoins du partenariat. Le MetaQuest 2 semble donc être la meilleure option. Je suis curieuse de voir ce qui se passe avec les options d’Apple, mais nous devrons attendre pour cela.

K

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d’histoire de l’art et d’études cinématographiques
514 343-2194

On Aug 31, 2022, at 12:05 PM, Lena Krause ***@***.******@***.***>> wrote:



prix et recherche sur les casques VR: https://docs.google.com/spreadsheets/d/1ShbI-JEIYuACUZkWTojnE9M7R3r0Qwkp/edit#gid=1266373557<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ShbI-JEIYuACUZkWTojnE9M7R3r0Qwkp%2Fedit%23gid%3D1266373557&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C177c39e5251b44adfc0208da8b6aa45b%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637975587377679642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0TB3PdHPq5WeQPp8DcBoyfhsAzjlaIpkJN6nQU1dozg%3D&reserved=0>

**Comment by emchateau** [comment]
Salut,

J’ai questionné Flavio Cardelicio qui fait sa thèse sur la réalité virtuelle. Il me confirme sans beaucoup d’hésitations que nous aurions intérêt à aller vers la dernière solution de MetaQuest (aka Occulus).

Pour le moment aller sur un matériel pour nous laisser voir quoi faire par la suite en fonction des développements.

Je pense qu’il y a plusieurs options pour le MetaQuest 2. Il faut regarder le détail.


Emmanuel Château-Dutier
Professeur agrégé

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by lenaMK** [comment]
le détail est là: https://docs.google.com/spreadsheets/d/1ShbI-JEIYuACUZkWTojnE9M7R3r0Qwkp/edit#gid=1266373557

**Comment by emchateau** [comment]
Oui, je viens de voir. 
Le prix me paraît très élevé par rapport à celui mentionné dans PC Mag (400$ US). 
Est-ce que le matériel ciblé comprend les manettes ?
Pas certain que nous ayons besoin des sangles élite mais qu’en pensez-vous ?

Dans mon message précédent je pensais y aller prudemment en achetant 1 appareil, plutôt que deux. De manière à nous laisser le temps de voir ce qui vient et de juger à l’usage.

**Comment by emchateau** [comment]
Désolé pour les édits.
Normalement INSO proposait le matériel.

**Comment by ktanton-work** [comment]
Je suis d’accord avec Emmanuel pour dire que nous devrions acheter un seul casque plutôt que deux pour le moment.
Je pense que les sangles d’élite sont importantes. Elles permettent d’éviter le mal des transports (motion sickness) chez les utilisateurs en maintenant le casque fermement attaché à la tête.

K

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d’histoire de l’art et d’études cinématographiques
514 343-2194

On Sep 1, 2022, at 10:32 AM, Emmanuel Château-Dutier ***@***.******@***.***>> wrote:



Oui, je viens de voir.
Le prix me paraît très élevé par rapport à celui mentionné dans PC Mag (400$ US).
Est-ce que le matériel ciblé comprend les manettes ?
Pas certain que nous ayons besoin des sangles élite mais qu’en pensez-vous ?

Dans mon message précédent je pensais y aller prudemment en achetant 1 appareil, plutôt que deux. De manière à nous laisser le temps de voir ce qui vient et de juger à l’usage.

**Comment by lenaMK** [comment]
Pour info: on a prévu du budget pour acheter 4 casques au total, soit 2 par année. Par contre, le budget est moindre: on a un momentant total de 958$ pour les deux, incluant la sangle etc. Sinon, il faut jouer avec le budget, en acheter 3 au lieu de 4 par exemple.

**Comment by emchateau** [comment]
L’idée était d’avoir deux appareils et de pouvoir les renouveler à la fin de la 3e année.
Compte tenu du prix, je pense qu’il vaut mieux partir sur un seul appareil pour le moment. Nous verrons ensuite ce que nous achetons de manière à réserver de l’argent si jamais Apple sort quelque chose d’assez cher par exemple. Ou si par expérience on se rend compte que nous aurions besoin d’un matériel plus cher ou plus spécifique.

**Comment by emchateau** [comment]
L’imprimante était normalement bien la même que la mienne, je l’avais choisie de la sorte. Il faut bien veiller à ce que le modèle soit Wifi (l’identifiant du produit est très proche).
LaserJet Pro M402dw (w pour wifi)

**Comment by lenaMK** [comment]
J'ai mis au propre le fichier pour la demande de [soumission INSO](https://docs.google.com/spreadsheets/d/1N35S7dw5ynTWNE8iaa0gSJIZjK7P65E2BkL7WZJA3Fc/edit?usp=sharing).
@emchateau pourrais-tu, s'il te plaît, me confirmer que les adaptateurs que j'ai choisi te conviennent? 
- 2x Apple lecteur micro-sd [Satechi](https://www.apple.com/ca/shop/product/HMYE2ZM/A/satechi-aluminium-usb-c-multiport-pro-adapter?fnode=108545752418cecd46d3a58c6be6b049da3ff8f582bfc579b2f0c95d8551ef393496d7660cb9b71d64b2085620bcd2541e4133be7cac659d24325edfaa2df0d93ccaab326fc91ef2ce2c3248c6957c5dcf792abcd2d27eea0fb0bc0b6c7f784f)
- 2x Apple [Belkin USB-C to Gigabit Ethernet Adapter](https://www.apple.com/ca/shop/product/HJKF2ZM/A/belkin-usb-c-to-gigabit-ethernet-adapter?fnode=38ea1c28a6104b387b9a1267bca9b8c7b1e091941302cc27e65f53c9098410178fb44a1b7e3ca0b069a31283fc9c2d259935dcfec90100f1d521ecd662f32081eb26c0b7f2ab3a0c5d7a9acd8bcf963d826e75efcfc6f4591e16e8c90bf00f42)

Si ces adaptateurs doivent aller dans les fournitures (compte FEI), alors je pense qu'il faudrait faire une soumission séparée.
Pour ma part, ce sont mes dernières questions, je serai prête à écrire à Georges après ta réponse Emmanuel

**Comment by emchateau** [comment]
- Visiblement il n’y a pas d’autre modèle pour le USB-C / Ethernet. J'espère juste que ce matériel peut être déclaré sur le réseau UdeM. Je n'ai aucune idée de comment ça marche et le type de la boutique informatique à l’Université était incapable de me répondre lorsque je lui ai demandé.

- Pour le lecteur micro-SD ça me paraît bon aussi.

Les adaptateurs devraient sans doute aller vers le budget du FEI. Je ne sais pas si Johanne a déjà renvoyé le formulaire que je lui avais envoyé pour l’approbation. Alors si c’est trop compliqué laissons tomber, on pourra sans doute ajuster ensuite d’une manière ou d’une autre.

**Comment by lenaMK** [comment]
Par "laissons tomber", tu veux dire qu'on passe la commande, incluant les adaptateurs (et qu'on s'arrangera après pour la répartition dans les budgets?

**Comment by emchateau** [comment]
Tout à fait

**Comment by lenaMK** [comment]
c'est envoyé

**Comment by lenaMK** [comment]
Évaluation détaillée de la soumission la semaine passée, corrections à demander: 
- moniteurs Apple Studio Display: nous avons demandé ceux avec la base ajustable pour le "tilt", mais sans le "height" (la différence de prix est conséquente)
- claviers "Magic Keyboard": sans touch ID (à nouveau, ils sont moins chers)
- nous prendrons juste 2 souris et non 3
- MacBook Pro: nous avons demandé le modèle M2 avec 16GoRAM et 512Go SSD (dans ce devis, vous avez mis 8Go RAM et 256Go SSD)
- pourriez-vous me confirmer la compatibilité du stylet "Apple Pencil" avec les iPad Pro de 6e génération svp? C'est indiqué uniquement pour les 3e-4e-5e génération donc je veux m'assurer de leur compatibilité
- je vous avais demandé de me détailler le fonctionnement de la licence Adobe, je n'ai pas encore reçu la réponse à ce sujet

En comparant avec les [prix Apple Education](https://docs.google.com/spreadsheets/d/1N35S7dw5ynTWNE8iaa0gSJIZjK7P65E2BkL7WZJA3Fc/edit#gid=815614713), INSO est très cher: 500$ de différence entre le prix Apple Education et le prix FCI. 

@emchateau as-tu une proposition de fomulation pour insister côté prix? 

J'ai écrit ça pour le moment: En ce qui concerne les prix, nous avons comparé avec les prix Apple éducation et avons observé une différence avec le prix FCI de 500$ pour chaque ordinateur MacStudo.

**Comment by ktanton-work** [comment]
Bonjour,

L'iPad Pro (6e génération) nécessite l'iPad Pencil de deuxième génération.

Cordialement,
Kristine

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d'histoire de l'art et d'études cinématographiques
514 343-2194

On Nov 14, 2022, at 10:52 AM, Lena Krause ***@***.******@***.***>> wrote:



Évaluation détaillée de la soumission la semaine passée, corrections à demander:

  *   moniteurs Apple Studio Display: nous avons demandé ceux avec la base ajustable pour le "tilt", mais sans le "height" (la différence de prix est conséquente)
  *   claviers "Magic Keyboard": sans touch ID (à nouveau, ils sont moins chers)
  *   nous prendrons juste 2 souris et non 3
  *   MacBook Pro: nous avons demandé le modèle M2 avec 16GoRAM et 512Go SSD (dans ce devis, vous avez mis 8Go RAM et 256Go SSD)
  *   pourriez-vous me confirmer la compatibilité du stylet "Apple Pencil" avec les iPad Pro de 6e génération svp? C'est indiqué uniquement pour les 3e-4e-5e génération donc je veux m'assurer de leur compatibilité
  *   je vous avais demandé de me détailler le fonctionnement de la licence Adobe, je n'ai pas encore reçu la réponse à ce sujet

En comparant avec les prix Apple Education<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1N35S7dw5ynTWNE8iaa0gSJIZjK7P65E2BkL7WZJA3Fc%2Fedit%23gid%3D815614713&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7Cdc803296936d49721b9708dac6582d07%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C638040379254136187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xjCTFH119HdfQcqkNcFUyz9karyhyLAUEgCdoGBOA04%3D&reserved=0>, INSO est très cher: 500$ de différence entre le prix Apple Education et le prix FCI.

@emchateau<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femchateau&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7Cdc803296936d49721b9708dac6582d07%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C638040379254136187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qaoFucj9a6gqkhiGmdaWO%2Bq%2BEBvoMiYGkmcZD%2Fg5wYM%3D&reserved=0> as-tu une proposition de fomulation pour insister côté prix?

J'ai écrit ça pour le moment: En ce qui concerne les prix, nous avons comparé avec les prix Apple éducation et avons observé une différence avec le prix FCI de 500$ pour chaque ordinateur MacStudo.

**Comment by lenaMK** [comment]
J'ai mis à jour le [document](https://docs.google.com/spreadsheets/d/1N35S7dw5ynTWNE8iaa0gSJIZjK7P65E2BkL7WZJA3Fc/edit#gid=815614713) avec les montants pour la nouvelle soumission. On dépasse de 3000$ par rapport au devis de 2020, par contre on a obtenu plus de rabais également. Un souci pour la licence Adobe, je ne crois pas que ça correspond à ce que tu voulais @emchateau . On en parle à la prochaine réunion, nous commençons a véritablement avoir tous les prix!

**Comment by emchateau** [comment]
En effet, ce n’est pas ce qui avait été négocié avec les licences Adobe. Mais ils n'ont pas vraiment répondu à la question du nombre de postes. Il faut faire un suivi avec eux.
Le dépassement de 3 000 est ennuyeux. C’est près de 10% des postes prévus. Mais surtout je ne vois pas trop où on va les prendre. On en discute la semaine prochaine oui. Mais clairement on est proche, surtout avec les prix pour les écrans. Reste peut-être à préciser les choses pour le matériel de visio conférence.

**Comment by lenaMK** [comment]
puisqu'on distingue les achats restants des deux commandes qui ont été passées
