### ISSUE TITLE
Choisir le mobilier (suivi des soumissions)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#143]
J'ai listé les demandes effectuées et leur statut dans [locaux.md](https://github.com/ouvroir/labouvroir/blob/main/locaux.md). Je vais téléverser les propositions, par fournisseur, dans le [drive ](https://drive.google.com/drive/folders/1xSRnYjOaHDiy1hEYGy0MWNm_O0_XjNbt?usp=sharing) au fur et à mesure

**Comment by lenaMK** [comment]
[propositions](https://drive.google.com/drive/folders/1rWDJLSIQK-x3-Tv7idPD6PscX81ot2DY?usp=sharing) de chez oburo

> Pouvez-vous me dire ce que vous en pensez ou si vous avez des modifications à apporter ?
> tout commentaire ou changement est demandé avant que nous vous fassions les prix.
> nous allons vous donner le prix pour les 2 options pour la salle de conférence mais d'abord nous aimerions savoir si vous avez des changements à faire,

**Comment by lenaMK** [comment]
J'ai commencé à faire des captures d'écrans pour vous donner des [visuels](https://docs.google.com/document/d/1BPgpEhv_ewwcL6I3Gy6CBjRJ1raLojLiumJjijBdftw/edit?usp=sharing) dans les propositions de mohd. En fait je pense que selon ce qu'on choisit, le layout sera effectivement ajusté comme on le souhaite (je vais le préciser de toute façon mais je pense qu'elle voudra les premiers choix de mobilier pour refaire le layout). C'est très beau :)

**Comment by emchateau** [comment]
Pour oburo,
Demander que le bureau ne soit pas traité comme des box de travail individuels mais permette le travail collectif. Pointer la question de l’encombrement des fauteuils de la salle de conférence. Demander des options plus design et modernes pour le mobilier.
Amitiés,

Emmanuel Château
Professeur agrégé
Université de Montréal
@emchateau

**Comment by emchateau** [comment]
Oui, en effet ce n’est pas mal du tout.
Il ne faut pas oublier de solliciter un marchand de mobilier du même genre à Montreal.
Pour donner les avis sur les meubles, est-ce qu’il serait possible de mettre les propositions dans un tableau pour que nous renseignons chacun nos avis par une note sur 5 et un commentaire, stp.
Amitiés,

Emmanuel Château
Professeur agrégé
Université de Montréal
@emchateau

**Comment by emchateau** [comment]
Salut, 

je suis passé au travers du document t et j’ai créé des tableaux pour mettre les commentaires. Les propositions sont très intéressantes. Je ne suis pas entierement convaincu par les choix proposés pour le bureau, notamment pour les sièges sur lesquels j’ai un peu l’impression qu’on fait des économies pour améliorer les tables.

Je crois que cela m’a vaudrait le coup de prendre le temps de parcourir certains des catalogues des fabricants envoyés pour regarder d’autres options.

Il faut faire attention à ce que le conseil ne devienne pas payant.

Cordialement,
Emmanuel

**Comment by lenaMK** [comment]
premier tri complété et suivi de courriel envoyé, on continue avec 
- trium
- mohd
- triede

**Comment by lenaMK** [comment]
Salut, on a du nouveau côté Mohd. le layout a été ajusté comme nous l'avons demandé et nous avons désormais les prix, j'ai fait un récapitualatif dans un [tableur](https://docs.google.com/spreadsheets/d/1AjO9DI-AfkLCVhrdP3BgAPPNSaD6iuGE4PIsBBazFt0/edit#gid=0) pour faciliter l'évaluation des options. 
Le temps entre la commande et la livraison est estimé à 3 mois. 
On en discute demain!

**Comment by lenaMK** [comment]
On a également du nouveau chez [Triede](https://docs.google.com/document/d/1_qCgKj77OkRPs6Un7uceu_Bp_ApZ-He_hdZws8QdgNg/edit#heading=h.8icw6ghh4tbp) C'est très cher, mais faisable si on garde les chaises de conférence noires dans la salle de conférence
@emchateau @ktanton-work si vous pourriez regarder les budgets (pour Mohd: [tableur](https://docs.google.com/spreadsheets/d/1AjO9DI-AfkLCVhrdP3BgAPPNSaD6iuGE4PIsBBazFt0/edit#gid=0)) et propositions pour la réunion mardi prochain (après la discussion avec William) ce serait super merci

**Comment by emchateau** [comment]
Merci Lena,
- Pourrais-tu réinsérer dans le tableau les liens vers les produits stp (je les avais copiés dans le document Google Doc).
- Pour mieux nous rendre compte de la profondeur des tables proposées, serait-il possible de nous rappeler les dimensions actuelles des tables qui sont dans la salle de conférence, stp.

**Comment by lenaMK** [comment]
[présentation des options](https://www.canva.com/design/DAFQ6RvE8yA/uNW5vvRlXvvX4EKlBS5dEw/edit?utm_content=DAFQ6RvE8yA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by lenaMK** [comment]
J'ai complété la [présentation des solutions de mobilier](https://www.canva.com/design/DAFQ6RvE8yA/uNW5vvRlXvvX4EKlBS5dEw/edit?utm_content=DAFQ6RvE8yA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) avec un bref paragraphe descriptif @emchateau je pense que ça complète bien pour préciser les avantages et inconvénients de chaque solution pour Johanne

**Comment by lenaMK** [comment]
courriel envoyé à Johanne

**Comment by lenaMK** [comment]
création d'un nouvel issue à jour maintenant que le prestatire est choisi: Trium, et qu'on va passer à la commande!
