### ISSUE TITLE
Diffuser annonce portes ouvertes et rentrée 2022

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#144]
courriel de présentation du labo (HAR | CIECO)
- journée portes ouvertes
- fika + clinique numérique les mardis
- liens vers site web et mobilizon...

rédiger une présentation de la clinique pour circonscrire le concept 
- regarder si on peut créer un événement récurrent pour les fika sur mobilizon
- événement de la rentrée (mobilizon)

**Comment by lenaMK** [comment]
démonstration de projets et d'équipement pendant la journée portes ouvertes (13 septembre): 
- démo Righettino (figma @KenanOudin et prototype @WilliamDiakite ?)
- démo modèle 3D Mauricio (sur le grand Mac?)
- @ktanton-work as-tu des choses que tu voudrais montrer ? 
- demander à Talitha si elle peut présenter son travail @emchateau 
- je peux présenter mon atlas ou MONA ou autre 
- scanTents (1 monté, pour permettre de le tester) 

Qu'en dites-vous, d'autres idées ou envies? 
Est-ce qu'on demande à Josée ou quelqu'un d'autre de présenter CIÉCO?

**Comment by lenaMK** [comment]
@emchateau veux-tu réviser le brouillon de l'[événement](https://mobilizon.fr/events/a04d4a3a-c598-458f-a332-8c724e8806eb) ?

**Comment by emchateau** [comment]
Salut le lien n'est pas valide.
Nous voulions le faire @ktanton-work et moi pour pouvoir configurer la clinique.
Pour l'annonce de righettino, il faut que nous ayons la confirmation de Denis.

**Comment by emchateau** [comment]
Je ne pourrais pas relire avant samedi

**Comment by ktanton-work** [comment]
Je peux présenter mes bases des données et montrer un modèle en 3D.

**Comment by lenaMK** [comment]
c'est un événement en brouillon donc il faut être connecté pour le voir. Je n'y présente pas la clinique (je pensais que ce serait dans le courriel d'invitation aux portes ouvertes que je mentionnerai la clinique et le fika), seulement la journée portes ouvertes, de la façon suivante: 

Bonjour à toutes et à tous,

À l‘occasion de la rentrée 2022, l’Ouvroir d’histoire de l’art et de muséologie numériques vous invite à sa journée portes ouvertes le mardi 13 septembre de 11h30 à 17h30 au C-8132 (pavillon Lionel-Groulx, Université de Montréal).

Au programme tout au long de la journée:

    présentation du laboratoire et des locaux partagé avec le CRIHN depuis la fin du printemps passé

    démonstrations de projets et d'équipement

    rencontre avec les membres de l'équipe

    café, thé et pâtisseries (apportez vos tasses réutilisables)

Au plaisir de vous accueillir à cet événement,

L’équipe de l’Ouvroir

**Comment by lenaMK** [comment]
complété
