### ISSUE TITLE
Acheter support écran TV

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#145]
Voici le support prévu dans le devis initial: [ViewSonic VB-STND-001](https://shop.inso.ca/catalogue/item/4721002/ViewSonic-VB-STND-001/VB-STND-001).
La seule alternative que je vois, pour une charge environ équivalente, serait [StarTech](https://shop.inso.ca/catalogue/item/5922461/StarTech.com-Pied-TV-Mobile-Chariot-Support-T%C3%A9l%C3%A9-Robuste-%C3%89crans-60-100%26quot-100kg-Support-TV-%C3%89cran-Plat-sur-Pied-Roulettes-Hauteur-R%C3%A9glable-Support-T%C3%A9l%C3%A9vision-Universel-%C3%89tag%C3%A8res-STNDMTV100-/STNDMTV100) 

Personnellement, je trouve que le ViewSonic a l'air plus robuste. 
Il est disponble en stock donc je pourrais probablement l'avoir rapidement

**Comment by ktanton-work** [comment]
Je suis d’accord avec toi. Un support robuste, et plus important, disponible en stock, est la meilleure solution.

Merci,
Kristine

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d'histoire de l'art et d'études cinématographiques
514 343-2194

On Aug 31, 2022, at 9:45 AM, Lena Krause ***@***.******@***.***>> wrote:



Voici le support prévu dans le devis initial: ViewSonic VB-STND-001<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshop.inso.ca%2Fcatalogue%2Fitem%2F4721002%2FViewSonic-VB-STND-001%2FVB-STND-001&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C18bc6b5bbbea49993a9708da8b571dce%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637975503518376160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cb1Ph%2FKImIeRJAM0wmv2TNI8ZElL9d3MEGncIg56ZOI%3D&reserved=0>.
La seule alternative que je vois, pour une charge environ équivalente, serait StarTech<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshop.inso.ca%2Fcatalogue%2Fitem%2F5922461%2FStarTech.com-Pied-TV-Mobile-Chariot-Support-T%25C3%25A9l%25C3%25A9-Robuste-%25C3%2589crans-60-100%2526quot-100kg-Support-TV-%25C3%2589cran-Plat-sur-Pied-Roulettes-Hauteur-R%25C3%25A9glable-Support-T%25C3%25A9l%25C3%25A9vision-Universel-%25C3%2589tag%25C3%25A8res-STNDMTV100-%2FSTNDMTV100&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C18bc6b5bbbea49993a9708da8b571dce%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637975503518376160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kO9xpAKfhuHS%2BZuqs5gT9NlMWiwg7hE3qPdBXw38kLE%3D&reserved=0>

Personnellement, je trouve que le ViewSonic a l'air plus robuste.
Il est disponble en stock donc je pourrais probablement l'avoir rapidement

**Comment by lenaMK** [comment]
@emchateau  est-ce que le support viewsonic te convient aussi?

**Comment by emchateau** [comment]
En principe oui, comme il serait compatible avec l’écran que nous allons acheter. Il faut simplement contrôler qu’il le soit avec celui que nous allons décrocher.
J’ai demandé à Michael s’il avait la facture de son écran. Mais on pourrait regarder la réf au local (il est actuellement en we)

**Comment by emchateau** [comment]
Avec un peu de chance aussi, le support mural actuel serait aussi compatible avec un nouvel écran un peu plus grand...

**Comment by lenaMK** [comment]
Modèle de la TV: https://www.samsung.com/ca/support/model/UN65NU6900FXZC/ 
Demande faite par téléphone pour la compatibilié avec le support ViewSonic, en attente d'en recevoir la confirmation et le devis (avec l'installateur et le rabais FCI)

**Comment by lenaMK** [comment]
Nous avons reçu une première soumissission (sans le rabais FCI, il l'ajoutera quand on valide le contenu de la soumission) on en a pour 964$ pour l'écran et presque 700$ de frais (montage du chariot, désinstallation de l'écran sur le mur, montage de l'écran sur le chariot). C'est le bon modèle de chariot, y a-t-il autre chose à vérifier @emchateau ?

**Comment by emchateau** [comment]
Super ! par contre j'ai un problème avec les frais de montage du chariot et de montage de l’écran qui me paraissent assez délirants. 

Il faut leur demander un effort sur ça ou au moins des explications. Est-on par ailleurs certain qu’il ne faudra pas passer par les menuisiers pour le mur ?

**Comment by lenaMK** [comment]
Je vais répondre en ce sens. Je crois que le menuisier ne serait pas une bonne personne pour s'ccuper de l'installation d'un écran TV sur un chariot mobile,..

**Comment by lenaMK** [comment]
@emchateau pourrais-tu essayer de rappeler Colin ou Georges svp? Merci!

**Comment by lenaMK** [comment]
sera dans la commande INSO de matériel audio-visuel
