### ISSUE TITLE
Préparer et diffuser l'annonce du midi-causierie 

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#148]
texte à définir

**Comment by lenaMK** [comment]
Le [brouillon](https://mobilizon.fr/events/cb187e0c-2373-45b3-ad8b-a57d60edeca8) est en ligne @emchateau 
Je ne suis pas sûre de comment bien valoriser le travail de William: préciser qu'il est ingénieur et développeur web, puis mettre Chaitanya à la ligne et mettre développeur?

**Comment by emchateau** [comment]
Je viens de faire des propositions

**Comment by lenaMK** [comment]
c'est bon pour moi, je peux publier l'événement?

**Comment by emchateau** [comment]
go

**Comment by emchateau** [comment]
Faire un courriel à Denis peut-être pour lui rappeler de bien le mettre à son agenda

**Comment by lenaMK** [comment]
je vais lui envoyer. 
Pourquoi ça n'apparaît pas ici: https://mobilizon.fr/@ouvroir_lab/events? J'ai un bug (de mon côté du moins)

**Comment by lenaMK** [comment]
ah mais attends, on fait ça en anglais??

**Comment by emchateau** [comment]
Non, chacun parlera dans sa langue.
Il y avait un problème sur la date de début que je viens de corriger. Normalement il s’affiche.
