### ISSUE TITLE
Annonce Fika

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#149]
Salut, j'ai préparé un brouillon d'événement [Mobilizon](https://mobilizon.fr/@ouvroir_lab) pour le fika mais je n'étais pas très inspirée. Avez-vous des idées de ce que je pourrais rajouter ?

**Comment by ktanton-work** [comment]
Je suis d’accord avec la proposition d’Emmanuel pour l’annonce Fika.

K

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d’histoire de l’art et d’études cinématographiques
514 343-2194

On Sep 15, 2022, at 10:03 AM, Emmanuel Château-Dutier ***@***.******@***.***>> wrote:



Salut, Voici ma proposition :

Chaque semaine le laboratoire organise une pause café et pâtisserie pour se rencontrer et socialiser, les mardis de 15h à 16h.

Le Fika est une [tradition suédoise<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.swedishfood.com%2Ffika&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C2470fa32666c4d34023c08da97231f2c%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637988474343139347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DPjUekp9fn3oLsko6MgO4yPX%2Bj%2BR3HMeMGBwu4MyQgo%3D&reserved=0>](https://www.swedishfood.com/fika<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.swedishfood.com%2Ffika&data=05%7C01%7Ckristine.tanton%40umontreal.ca%7C2470fa32666c4d34023c08da97231f2c%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637988474343139347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DPjUekp9fn3oLsko6MgO4yPX%2Bj%2BR3HMeMGBwu4MyQgo%3D&reserved=0>) destinée à rassembler une collectivité dans une ambiance chaleureuse et conviviale afin de faciliter les rencontres et les discussions.

Ces rencontres avec l’équipe sont ouvertes à tous. Venez rencontrer ou retrouver l’équipe du laboratoire et échanger sur vos projets !

________________________________

Ne peut-on pas créer un événement récurrent avec Mobilizon ?

**Comment by lenaMK** [comment]
@emchateau non pas d'événements récurrents sur Mobilizon malheureusement. Une fois qu'on est d'accord sur l'organisation, je vais faire des dupliqués

**Comment by emchateau** [comment]
OK
