### ISSUE TITLE
Proposition - accueillir un atelier de broderie

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#153]
mailto:maude.darsigny.trepanier@gmail.com

https://www.facebook.com/events/491360569107964

**Comment by lenaMK** [comment]
@emchateau @ktanton-work je n'ai pas eu le temps de vous en parler hier mais il y avait la semaine passée ce superbe atelier de broderie à l'UQAM que j'ai manqué. J'en ai parlé avec Johanne et Josée pendant le lunch et elles m'ont dit qu'elles trouveraient ça super que nous les invitions à en organiser un à l'Ouvroir. Qu'en pensez-vous? Je peux contacter Maude ou le CIÉRA pour en savoir plus si l'idée vous plaît. Cela représente un atelier supplémentaire pour le labo mais sans grandes contraintes organisationnelles puisque le format est pré-existant :)

**Comment by emchateau** [comment]
Salut,
Je trouve que c’est une très bonne idée. Quoi de mieux qu’un atelier de broderie dans un ouvroir !
Il faut toutefois s’attendre à ce que cela présente un coût. Le laboratoire n’a pas de ligne budgétaire pour cela. Cela impliquerait de trouver des sous.
Bien amicalement,
Emmanuel

**Comment by ktanton-work** [comment]
Cela fait longtemps que je n’ai pas fait de broderie :)
Je suis d’accord avec Emmanuel (oui, atelier, attention au budget).

Bien amicalement,
Kristine

Kristine Tanton
Professeure adjointe | Assistant Professor.
Département d'histoire de l'art et d'études cinématographiques
514 343-2194

On Sep 28, 2022, at 5:08 PM, Emmanuel Château-Dutier ***@***.******@***.***>> wrote:


Salut,
Je trouve que c’est une très bonne idée. Quoi de mieux qu’un atelier de broderie dans un ouvroir !
Il faut toutefois s’attendre à ce que cela présente un coût. Le laboratoire n’a pas de ligne budgétaire pour cela. Cela impliquerait de trouver des sous.
Bien amicalement,
Emmanuel

**Comment by lenaMK** [comment]
J'ai pris contact avec le CIERA pour obtenir d'avantage d'informations, j'attends des réponses

**Comment by lenaMK** [comment]
Mais qu'est-ce que je suis enjouée de cet intérêt de la part du département de muséologie pour ce projet! Merci beaucoup :)
En effet, la première fois que j'ai animé cet atelier dans le cadre d'une conférence du Ciéra j'étais accompagné de ma collègue Jennifer Buckell pour l'aspect de transmission culturelle en lien avec les pratiques traditionnelles autochtones mais, je crois que, selon votre budget et vos buts, les ateliers pourrais se dérouler uniquement avec la partie broderie?
Donc, je laisse Arnaud, notre cher coordonateur au CIÉRA en CC mais je suis ouverte à toutes les possibilités!

À très bientôt,
Maude

Maude Darsigny-Trépanier (MA)
Candidate au Doctorat en Histoire de l'art
Assistante de recherche pour Caroline Nepton-Hotte
Membre du GRIAAC et du CIERA

**Comment by lenaMK** [comment]
@emchateau  et @ktanton-work je me demade ce que je pourrais répondre à Maude? 
> En effet, la première fois que j'ai animé cet atelier dans le cadre d'une conférence du Ciéra j'étais accompagné de ma collègue Jennifer Buckell pour l'aspect de transmission culturelle en lien avec les pratiques traditionnelles autochtones mais, je crois que, selon votre budget et vos buts, les ateliers pourrais se dérouler uniquement avec la partie broderie?

Avez-vous une préférence entre la partie broderie ou l'[atelier "complet"](https://www.facebook.com/events/491360569107964) tel qu'il avait été organisé à l'UQAM? 
En matière de budget, on pourrait peut-être demander au département s'ils auraient un petit montant pour ça?

**Comment by emchateau** [comment]
En effet, visiblement c’est payant.
Demande à lui parler, cela sera plus simple pour tâter le terrain. Comprendre comment ça marche, qui est payé, le coût du matériel, etc.
En effet on pourrait demander au département. Je ne sais pas trop comment le justifier. Pour cela demander plus d'info me paraît un préalable.

**Comment by ZoeRenaudie** [comment]
Lena nous fait l'atelier broderie le 03 avril !
