### ISSUE TITLE
demander remboursement formations CalculQc

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#157]
- [ ] retrouver la situation pour la demande de remboursement pour la formation CalculQc
- [ ] utiliser les fonds du FEI au besoin si autorisé

**Comment by emchateau** [comment]
Les fonds du FEI sont éligibles.

**Comment by emchateau** [comment]
@lenaMK veux-tu que nous essayons ?

**Comment by ZoeRenaudie** [comment]
Toujours d'actualité?

**Comment by lenaMK** [comment]
Non j'avais envoyé les documents il y a très longtemps et j'abandonne le projet
