### ISSUE TITLE
Confirmer la date du midi-causerie avec Antoine Courtin

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#161]
Pourrais-tu me donner la date prévue pour le midi-causerie svp? 
Merci

**Comment by lenaMK** [comment]
Salut @emchateau  je pensais préparer la comm, as-tu un titre pour la conférence d'Antoine?

**Comment by emchateau** [comment]
Pas vraiment, je vais le relancer. Amitiés
