### ISSUE TITLE
Discuter du PDG initial

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#165]
La demande de financement prévoit la mise en place d’un plan de gestion des données de recherche (PGD). Celui-ci doit faire l’objet d’une mise à jour annuelle.

Des recherches préliminaires ont été effectuées sur la gestion des données de recherche
https://drive.google.com/drive/folders/1t4im7IFjxJ4Nu9eQ6Jzust0aQnthoSPu

Un premier PGD a été agrégé rédigé avec l’assistant PGD de Portage (aka Digital Research Alliance).
https://alliancecan.ca/fr/services/gestion-des-donnees-de-recherche/assistant-pgd

**Comment by emchateau** [comment]
Salut, j'ai mis les infos que j'avais.
As-tu pu regarder ? Je propose que nous en discutions mardi.

**Comment by lenaMK** [comment]
oui j'ai tout regardé, on s'en parle demain si on a le temsp, sinon la semaine d'après

**Comment by lenaMK** [comment]
À lire @lenaMK 
- [note sur la sécurisation des drive](https://docs.google.com/document/d/13tcOuJ5RTnVet8-cs1OH5lU4YVcIi-vlXDl7m5C95Cs/edit#heading=h.jleserlzwrkm)
- [passport pour la science ouverte](https://www.ouvrirlascience.fr/passeport-pour-la-science-ouverte-guide-pratique-a-lusage-des-doctorants/#:~:text=Le%20Passeport%20pour%20la%20science,et%20d'outils%20directement%20activables.)

**Comment by lenaMK** [comment]
- ajouter Zotero
- Drive

**Comment by emchateau** [comment]
Pour information, j’ai produit un certain nombre de notes sur la gestion des données de recherche CIECO > Cellule numérique.
- Il y a une esquisse de politique
- Un question/réponse
- Une méthode pour l’inventaire des données.

Nous avons eu une réunion avec le BRDV le 31 août dont tu pourras également trouver le compte-rendu. J’essaye de faire une mise à jour du PGDR. Mais j'aurais probablement besoin d’en discuter avec vous.
