### ISSUE TITLE
DH 2023 poster Ouvroir (délai 4 nov)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#168]
J'ai créé un [dossier sur le drive](https://drive.google.com/drive/folders/1BcINPYcu39HFdQZmvEzxLNvVzTgP0xmR) pour les présentations du labo à des conférences et événements. Pour l'instant il contient les liens vers la vidéo et le Canva du C3N, et une version pdf de la présentation du C3N. 
Il faudra aussi y ajouter l'abstract d'Humanistica @emchateau 
Il contient aussi un [doc DH2023](https://docs.google.com/document/d/1H6KafW3gg_N1LFYb-7NZgYtsFUtiFZ7uSv-cGJNm8rI/edit) pour qu'on y travaille sur l'abstract du poster.

**Comment by lenaMK** [comment]
Salut, petite relance pour le poster DH :) @ktanton-work  @emchateau il faudrait notamment avoir l'abstract humanistica. 
Aussi, on l'écrit en anglais ou en français?

**Comment by emchateau** [comment]
Le produit final devrait être en anglais. Mais si plus simple a cet étape cela peut être en français. 
Pour l’abstract d’humanistica, il s’agissait de la présentation du laboratoire.
