### ISSUE TITLE
Envisager les solutions possibles pour les écrans tactiles

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#170]
Voir le document https://docs.google.com/document/d/139hdEipGoOtx-cPs5-tWiqJsKdqJ0u5MZj-efAPBOzc/edit?usp=sharing

**Comment by lenaMK** [comment]
suite à la réunion admin (courriel envoyé)

- Quels sont les prix des écrans PCAP (dans les trois dimensions 65, 75 et 86)? 
- Combien coûte le support motorisé qui permet d'incliner l'écran à 90°?
- Avez-vous des supports muraux inclinables (pour que l'écran ne soit pas vertical sur le mur mais légèrement incliné et que ça devienne ainsi plus agréable d'écrire / de travailler dessus)?  Jusqu'à quelle dimension d'écran fonctionnent-ils et quels seraient les coûts (du support et de l'installation si celle-ci diffère du devis précédent)?
- À titre indicatif, quels sont les prix des écrans avocors (équivalents aux PCAPS 65, 75 et 86 susmentionnés)? 
- Puisque nous considérons des options plus coûteuses, nous aimerions aussi obtenir les prix d'écrans viewSonic qui ne sont pas tactiles en 75'' (pour la salle de conférence). Cela nous permettrait d'avoir des options pour équilibrer  le budget.

**Comment by lenaMK** [comment]
On a reçu le détail des prix, ils sont dans le [pad](https://demo.hedgedoc.org/vMcWp0nwRe-XJGhdmpeC8w#) pour en discuter à la prochaine réunion

**Comment by lenaMK** [comment]
nous avons sélectionné les écrans PCAP75 ave un écran à support motorisé
