### ISSUE TITLE
Peinture du C-8132 (salle conf)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#181]
Attendre les informations sur les délais de livraison et confirmation du blanc, puis passer une commande Maximo (viser la semaine de relâche?)

**Comment by lenaMK** [comment]
@emchateau j'ai vu les nouveaux logos CIECO, on pourrait aussi songer à faire les murs en gris CIECO? c'est suffisamment passe partout pour pas crier CIECO, mais si ça peut plaire à Johanne?

**Comment by emchateau** [comment]
Je pense qu’il vaut mieux partir sur le blanc. J'ai demandé rdv à Johanne

**Comment by lenaMK** [comment]
@emchateau on part toujours sur du blanc? je suis prête à faire la demande Maximo puisque George  m'a répondu et que le chariot devrait être livré (et l'installation de la TV dessus) dans 2 semaines.

**Comment by lenaMK** [comment]
Discussion avec Johanne qui était au bureau hier. Elle dit qu'elle avait validé l'anthracite, mais en regardant la salle nous avons convenu que si on y va avec l'anthracite, que ce serait uniquement le mur de la télé et la partie du fond serait en blanc. Sinon, tout en blanc car ça semble plus simple, ça éviterait également les délais de commande de la peinture. Est-ce qu'on peut aller de l'avant avec du blanc @emchateau @ktanton-work ?

**Comment by emchateau** [comment]
Salut Lena,
Je ne comprends pas ton message. Si on avait mis de l’anthracite cela aurait été sur le mur de la télé seulement.
Lors d’une dernière discussion nous étions partis pour du tout blanc.

**Comment by lenaMK** [comment]
C'est bon pour du tout blanc alors!

**Comment by lenaMK** [comment]
Demande lancée:  DS-368307

**Comment by lenaMK** [comment]
Travaux de peinture commencent demain, 26 avril. La TV a été démontée et la salle libérée

**Comment by lenaMK** [comment]
faite fin avril
