### ISSUE TITLE
licences adobe

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#182]
Demander à INSO le nombre d'appareils inclus dans la licence
 4452325 | 65272451BB01A12 | 16.1 | LICENCE LOGICIEL ADOBE CREATIVE CLOUD ALL APPS - NAMED SUBSCRIPTION - 12 MONTHS NAMED LICENSE NEW LEVEL 1
la quantité (3) pointe vers 3 ans?

**Comment by lenaMK** [comment]
prix canadiens [Adobe](https://www.adobe.com/ca/creativecloud/plans.html#)

**Comment by emchateau** [comment]
Résolu, acquisition faite.
