### ISSUE TITLE
Historique des activités du laboratoire 2022-2023

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#189]
Salut,

Emmanuel m'a dit qu'il avait besoin rassembler des informations sur ce qui a été fait au labo en 2022-2023. J'ai fait une première liste dans le document [historique](https://github.com/ouvroir/labouvroir/blob/main/historique.md). Pourriez-vous regarder s'il reste des choses à ajouter selon vous svp? 
Merci beaucoup

**Comment by emchateau** [comment]
Merci beaucoup Lena.
Je vais essayer de comptabiliser le nombre d’activités. 
Pour les cliniques, peux-tu préciser le nombre d’étudiants suivis, stp ?

Amitiés,
Em

**Comment by emchateau** [comment]
Voir les RA CIECO. Mais maintenir un document propre au laboratoire serait utile.
