### ISSUE TITLE
Publier un répertoire de projets DAH

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#19]
J’ai commencé à élaborer une liste de projets en histoire de l’art numérique. Celui-ci est décrit en XML-TEI.
- [ ] compléter les projets présentés
- [ ] faire la transformation pour publier
- [ ] uniformiser le répertoire
- [ ] ajouter une catégorisation avec tadirah
- [ ] nouer des partenariats

**Comment by lenaMK** [comment]
dans un repo séparé: https://github.com/ouvroir/dahprojects

**Comment by emchateau** [comment]
Ce n’est pas terminé, c’est en cours

**Comment by emchateau** [comment]
Ok
