### ISSUE TITLE
Commande de mobilier avec Trium 

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#191]
Il reste une validation pour finaliser le budget, qu'on espère avoir d'ici mardi 30 mai

**Comment by lenaMK** [comment]
budget validé; demande détaillée envoyée à trium après discussion

**Comment by lenaMK** [comment]
finalisation des dessins avec l'équipe trium, en attente de la soumission qui devrait arriver dans les prochains jours. Ensuite, il faudra voir avec Jessica car il faut un dépôt de 30%. J'ai envoyé un courriel pour lui poser la question

**Comment by lenaMK** [comment]
envoi de la facture pour le dépôt: à signer @emchateau

**Comment by emchateau** [comment]
J'avais signé la facture et retournée à Trium. Il y a-t-il autre chose à faire ?

**Comment by lenaMK** [comment]
non c'était pour l'approbation à Jeff mais c'est fait aussi. Reste plus qu'à attendre je crois.

**Comment by lenaMK** [comment]
Jeff a passé un bon de commande ouvert, à voir si c'est accepté du côté des finances

**Comment by lenaMK** [comment]
Le paiement devrait être passé (vendredi, selon Jeff et Emmanuel). Courriel de suivi envoyé à Trium aujourd'hui

**Comment by lenaMK** [comment]
La commande a été passée! Il faut compter environ 6 semaines pour la livraison (mi-octobre). On aura des nouvelles avec une date plus précise d'ici trois semaines, donc environ 20 septembre

**Comment by lenaMK** [comment]
la livraison et installation est prévue pour le 18 octobre

**Comment by emchateau** [comment]
youyou !

**Comment by lenaMK** [comment]
Katrina a un problème avec son meuble de rangement (ne ferme plus à clef) et sa prise USB n'a jamais fonctionné @WilliamDiakite

**Comment by emchateau** [comment]
J’apprends que la prise USB ne fonctionne pas. Pour le meuble et la rallonge, Wiliam devait faire un suivi.

**Comment by WilliamDiakite** [comment]
Un mail a été envoyé à trium ce jour pour notifier des problèmes suivant :
- problème de rallonge pour connecter les bureaux
- problème d'USB
- problème de tiroirs.

La suite au prochain épisode.

**Comment by emchateau** [comment]
Trium est passé et refuse la prise en charge.
Les tiroirs fonctionnent. On laisse tomber et met en paiement.

Question @WilliamDiakite finalement la prise USB fonctionnait ?

**Comment by ZoeRenaudie** [comment]
oui elle fonctionnait. Le paiement est parti, je cloture
