### ISSUE TITLE
midi-causeries et ateliers 

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#195]
Dates possibles (tentative initiale) les mercredis

Automne 2023
- 6 septembre: présentation interne @ZoeRenaudie 
- 13 septembre: [midi-causerie avec Jean-Paul Fourmentraux](https://mobilizon.fr/events/864a22e7-fc93-4451-8a0e-aae0683e25c7)
- 20 septembre
- 27 septembre : club de lecture [*The Growing Pains of Digital Art History*, Wasielewski](https://www.zotero.org/groups/5040183/ouvroir-lectures/items/L5FDR5WY/attachment/PAQU8NXD/reader)
- 4 octobre
- ~~11 octobre~~ : colloque du CRIHN
- ~~18 octobre~~ : relâche
- 25 octobre:
- 1er novembre: midi-causerie avec Pierre Willaime sur Omeka
- 8 novembre: club de lecture [*There is a digital art history*](https://www.zotero.org/groups/5040183/ouvroir-lectures/items/FEJ7H7CU/library)
- [15 novembre]: grande conférence et Journée d'étude CIÉCO du 16 au 18 novembre
- 22 novembre
- 29 novembre
- 6 décembre : Noël au lab? 
- [13 décembre] : Fin de session et congé Lena

Hiver 2024
- 10 janvier
- 17 janvier
- 24 janvier
- 31 janvier : Andréa Gozzi
- ~~7 février~~ : grande conférence CIÉCO axe 2
- 14 février
- 21 février
- 28 février : atelier 4 Cieco
- ~~6 mars~~ : relâche et congé Lena
- 13 mars : Béatrice Denis
- 20 mars : Conf Cieco UQO

voir [calendrier](https://github.com/ouvroir/labouvroir/blob/main/calendrier.md)

**Comment by lenaMK** [comment]
présentation de la base de données de Zoë, inviter David Valentine aussi

**Comment by lenaMK** [comment]
atelier d'introduction à la cartographie Lena

**Comment by lenaMK** [comment]
club de lecture automne 2023
- article de Wasielewski: 27 septembre
- Impett et Offert
- Ingold

**Comment by lenaMK** [comment]
Atelier sur la segmentation de corpus, Alice
- banc d'essai: essayer des outils de segmentation

**Comment by emchateau** [comment]
Nous avons regardé avec Alice, le 25 octobre pourrait fonctionner pour un midi-causerie consacré à la segmentation de corpus. Par contre, je réalisais que cela ne permettrait pas forcément de travailler avec William dans l’apm. Il faudrait voir si la date conviendrait également à Alix et Léa.

**Comment by lenaMK** [comment]
> Nous avons regardé avec Alice, le 25 octobre pourrait fonctionner pour un midi-causerie consacré à la segmentation de corpus. Par contre, je réalisais que cela ne permettrait pas forcément de travailler avec William dans l’apm. Il faudrait voir si la date conviendrait également à Alix et Léa.

on déplace au 22 ou 29 novembre

**Comment by ZoeRenaudie** [comment]
Proposition midi causerie 2024

jan : Andrea Pozzi

fev-mars Beatrice : Retronews 

mars-avril Pierre Carl Langlais (alexander Doria) : IA 
@ecd prend rdv avec lui

avril-mai : wikidata shenagen Protos

mai-juin : Johanna Daniel quand aura terminer sa thèse sur Omeka au printemps. 

ecrire à Alice pour savoir qui elle voulait inviter pour l'automne prochain

inviter C2DH ? 

présentation d'OntoExhibit par leur équipe? https://complexhibit-project.github.io/OntoExhibit/index-en.html

Session de travail avec digitorials pas un midi causerie. 

2 M-C sur IIIF

**Comment by ZoeRenaudie** [comment]
@emchateau : prendre rdv pour midi causerie avec Pierre Carl Langlais (alexander Doria) ou Shonagen pour fin avril-mai

**Comment by emchateau** [comment]
Il s’agit de Benoit Deshayes aka Shonagon https://meta.wikimedia.org/wiki/User:Shonagon
Il me semble qu’il travaille actuellement au Louvre, en charge de la maintenance du site louvre.fr puis sur le portail des collections. Du coup, je ne sais pas s’il pourra intervenir.

**Comment by emchateau** [comment]
J’ai écrit à Shonagon pour lui demander.

**Comment by ZoeRenaudie** [comment]
Des nouvelles? On a personne pour avril-mai.

**Comment by ZoeRenaudie** [comment]
Non, ça me semble parfait!

**Comment by ZoeRenaudie** [comment]
inviter sylvain pour nous presenter son travail. Ximena aussi, post-doc cieco ? ou faire venir qqun de l'etranger? designeuse de belgique?

**Comment by ZoeRenaudie** [comment]
Les personnes a inviter sont désormais listées ici : https://github.com/ouvroir/labouvroir/edit/main/cr/notes/aInviterLab.md
Ceux qui ont eu lieu sont dans le calendrier du laboratoire.
