### ISSUE TITLE
Liste du matériel et système de location

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#207]
Liste du matériel
Noter qui a quoi, date emprunt et retour

**Comment by lenaMK** [comment]
J'ai fait un début ici: https://docs.google.com/spreadsheets/d/15GvJKFcucdtaSqEQygV_CwYjaVYuMDiH8IBUYN5QcEc/edit#gid=0

**Comment by WilliamDiakite** [comment]
@ZoeRenaudie nous a concoté un formulaire + spredsheet + agenda connectés qui fonctionnent à merveille. 
Je ferme cette issue.
