### ISSUE TITLE
corriger description BRDV

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#209]
il manque le s à numérique dans la description, 1ère phrase : https://recherche.umontreal.ca/nos-chercheurs/repertoire-des-unites-de-recherche/unite/is/ur14536/

**Comment by lenaMK** [comment]
@emchateau as-tu un accès direct pour corriger cette erreur? 

(
il manque le s à numérique dans la description, 1ère phrase : https://recherche.umontreal.ca/nos-chercheurs/repertoire-des-unites-de-recherche/unite/is/ur14536/
)

**Comment by emchateau** [comment]
Non, je n’ai pas accès. J’avais déjà demandé la correction mais ils ne l’ont faite que sur le titre.
Peux-tu écrire pour demander s’il te plaît ?
Et demander d’ajouter William à l’équipe en me mettant en copie.
Amitiés,
Emmanuel


Le 25 sept. 2023 à 09:40, Lena Krause ***@***.***> a écrit :



@emchateau<https://github.com/emchateau> as-tu un accès direct pour corriger cette erreur?

(
il manque le s à numérique dans la description, 1ère phrase : https://recherche.umontreal.ca/nos-chercheurs/repertoire-des-unites-de-recherche/unite/is/ur14536/
)

**Comment by lenaMK** [comment]
courriel envoyé le 25 septembre

**Comment by lenaMK** [comment]
les corrections sont faites (ajout du S, ajout de William dans le personnel).

Contacter Julie Pelletier si on a besoin de modifications
