### ISSUE TITLE
infolettre mi-octobre

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#212]
rappel portes ouvertes 
[midi-causerie](https://mobilizon.fr/events/d9767614-00c7-4661-9964-69a8f81dfa21) avec Pierre Willaime le 1er novembre

@emchateau  fais-moi signe si tu as quelques chose à ajouter, je pensais ensuite l'envoyer mercredi matin

**Comment by emchateau** [comment]
OK
