### ISSUE TITLE
Clef pour le local de rangement CRIHN

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#214]
Katrina aurait besoin d'un double de la clef du local de rangement C-8132-3 (où il y a les choses de ménage. Est-ce que je lui lance une commande clef, ou est-ce que je lui dis de le faire via Michael?

**Comment by emchateau** [comment]
Salut Lena,
Il faudrait que nous fassions le point sur ces clefs. As-tu mis en place un registre pour savoir qui a les clefs ? Josée aurait sans doute aussi besoin d’une clef. Nous pouvons faire la commande.

**Comment by lenaMK** [comment]
En effet josée m'a demandé une clef elle aussi. Je vais faire la commande et préparer un récapitulatif sur les clefs.

**Comment by ZoeRenaudie** [comment]
Inventaire des clefs  [https://docs.google.com/spreadsheets/d/1fntCWJ_NRuQrQSSV9UV25kpuIQpnRtJ1NQFODhECHaY/edit#gid=0]

**Comment by ZoeRenaudie** [comment]
2 doubles de clefs C-8132-3 commandées! 

J'ai mis en place une feuille de signatures de remise de clefs qui se trouve dans le casier de Lena.
