### ISSUE TITLE
Passation

### ISSUE THREAD

**Issue by ZoeRenaudie** [ouvroir/labouvroir#216]
Liste de sujets à aborder pendant la dernière semaine de Lena : 
- Zotero
- Hypothesis note display? :  https://hypothes.is/groups/pM5dq7b4/ouvroir
- Compta
- Changer numéro tel de ref google 
- Compte zoom
- ou ranger le fichier avec tous les codes? 
- pas droit de pousser sur DAHnotes
- droits github? 
- Icloud : numéro de recuperation
- mots de passe
- liste sympa mdp ouvroir

**Comment by ZoeRenaudie** [comment]
Zotero : Ok 

Hypothesis : Zoë ne voit que 19 articles dans le groupe au lieu de 444 écrits par Lena...

Compta : ok 

Google numéro : ok - num zoe

zoom : voir avec @emchateau 

sympa : OK

ou ranger le fichier avec tous les codes : Google password?

github : zoe team admin ok  mais pas owner

**Comment by emchateau** [comment]
Reste password manager
