### ISSUE TITLE
Suivi financements

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#219]
- [x] Rapport FCI
- [x] Document emploi dépenses FCI (date interne : 14 mai)
- [x] Rapport contribution Josée (22 avril)

À faire
- détail financement Michael 
- récapitulatif modification de dépense
- point emploi fonds William

**Comment by ZoeRenaudie** [comment]
Dépenser le budget travaux et matériaux : 

- [ ] mobilier cafe	: 500 
- [ ] ralonge  : 500
- [ ] chaise 1 trium : 250	
- [ ] chaises rouillard code fournisseur : 00066377	 : 1500	
- [ ] cable recharge apple x1 : papier
- [ ] Lampes
- [ ] NAS - STAND BY
- [x] carte sd

- [x] peinture : 1400 cad
- [x] stores x5 : 960 cad
- [ ] plaque ouvroir (se coordo avec le CRIHN) : 1600 cad
- [ ] porte vitree ou plafonnier lampe naturelle 
- [ ] stores interieur x1 ou 2 : 500 cad
- [ ] serrure électronique : 2300 cad
- [ ] prise ethernet x4 : 1400 cad
- [ ]

**Comment by ZoeRenaudie** [comment]
@ZoeRenaudie  trouver soummission viewsonic et inso visioconference et audio

**Comment by emchateau** [comment]
Préparation 16 avril, finaliser et envoyer

**Comment by emchateau** [comment]
J’y ai pensé. L’argent que j'ai versé sur le compte n’étant pas consommé, il ne doit pas être indiqué dans le montant. William n’a pas pu travailler sur mon projet cet été en raison du travail sur le site de la CRC, donc pas de décompte à faire.
Il y a deux versements de Michael à compter
- celui du matériel 
- celui du mobilier

**Comment by emchateau** [comment]
Pour les rapports FCI voir #224

**Comment by emchateau** [comment]
Envoyé
