### ISSUE TITLE
Gestion des mots de passe

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#222]
Le laboratoire doit gérer plusieurs mots de passe et comptes pour les différents services, les différents ordinateurs et matériels. Trouver une solution facile à maintenir et sécuritaire pour la gestion des mots de passe.

**Comment by ZoeRenaudie** [comment]
Mettre le markdown crypté dans github? William cherche une solution

**Comment by WilliamDiakite** [comment]
Quelques outils pour le chiffrement de fichiers sur github:
- [Git-crypt](https://github.com/AGWA/git-crypt)
> Where git-crypt really shines is where most of your repository is public, but you have a few files (perhaps private keys named *.key, or a file with API credentials) which you need to encrypt.

- [BlackBox](https://github.com/StackExchange/blackbox)
> These commands make it easy for you to Gnu Privacy Guard (GPG) encrypt specific files in a repo so they are "encrypted at rest" in your repository. However, the scripts make it easy to decrypt them when you need to view or edit them, and decrypt them for use in production.
[...] this project is to be a simple wrapper around gpg so you and your coworkers don't have to remember its all those inscrutable and confusing flags.

- [Transcrypt](https://github.com/elasticdog/transcrypt)
> A script to configure transparent encryption of sensitive files stored in a Git repository. Files that you choose will be automatically encrypted when you commit them, and automatically decrypted when you check them out. The process will degrade gracefully, so even people without your encryption password can safely commit changes to the repository's non-encrypted files.


J'ai le sentiment que Transcrypt est peut-être ce qu'il nous faut. Je fais des tests !

**Comment by WilliamDiakite** [comment]
On a essayé Transcrypt avec @ZoeRenaudie, ça marche du feu de Dieu !
@emchateau, on te fera le setup quand tu reviens.
