### ISSUE TITLE
Mettre à jour équipe site Ouvroir

### ISSUE THREAD

**Issue by ZoeRenaudie** [ouvroir/labouvroir#225]
Lena et Zoë : J'ai modif les textes.
Il manque Camille sur le site.

**Comment by ZoeRenaudie** [comment]
J'ai mis les fiches à jour, mais le site ne se rafraichit toujours pas malgré les manip de ce matin.

**Comment by emchateau** [comment]
Je pense que @WilliamDiakite n’a pas tout réglé. Cela dit qu’il manque un dossier Build.

**Comment by emchateau** [comment]
cf. https://github.com/ouvroir/website/issues/49
