### ISSUE TITLE
Trouver un nouveau pad pour le labo

### ISSUE THREAD

**Issue by ZoeRenaudie** [ouvroir/labouvroir#235]
Hedge doc demo ne nous permet plus la meme utilisation. Il faut trouver une autre solution.

**Comment by emchateau** [comment]
Plusieurs services alternatifs hébergent un HedeDoc https://www.chatons.org/taxonomy/term/236
En attendant que nous en proposions un à l’UdeM

**Comment by ZoeRenaudie** [comment]
Tri des chatons : 

Le pad de Nantes semble donner acces avec une inscription simple hedgedog
- https://pad.libreon.fr/ aussi
- https://md.roflcopter.fr/ aussi

Lequel tu préfères @emchateau ? 

Besoin de créer compte sur leur platforme : 
- https://md.picasoft.net/
- https://nomagic.uk/fr/services/#CollabMarkdown 
pad : https://hedgedoc.nomagic.uk/
- https://resilien.fr/

**Comment by emchateau** [comment]
J'aurais idéalement préféré un système d’authentification délégué qui permet d’utiliser un compte GitHub ou Google. Ce n’est le cas d’aucun visiblement. Ce sont toutefois des associations qui gèrent ces châtons, je pense que nous devrions leur faire un courriel de cordialité pour nous présenter. On peut sans doute utiliser celui de Rennes en attendant puis voir ensuite.

**Comment by ZoeRenaudie** [comment]
C'est lequel Rennes? Je peux leur écrire un petit mail.
