### ISSUE TITLE
Préparer rentrée Aut 2024

### ISSUE THREAD

**Issue by ZoeRenaudie** [ouvroir/labouvroir#237]
- [x]  arreter une date de réunion de rentrée admin et labo complet

- [x] trouver un autre jour que le mercredi matin pour la reunion hebdo (Zoë a cours le mercredi matin)

- [x] partager les nouvelles de rentrée par mail

**Comment by emchateau** [comment]
Il faudrait mettre à l’ODJ de mercredi la préparation du courriel de nouvelles.

**Comment by emchateau** [comment]
Il y a des discussions sur les dates de réunion du CRIHN qui envisagent peut-être le 3 septembre (date où nous avions prévu la rentrée). Je te tiens au courant.
