### ISSUE TITLE
Midi-Causerie Laura Delfino

### ISSUE THREAD

**Issue by ZoeRenaudie** [ouvroir/labouvroir#246]
Présentation de la boîte à outils du MBAM : https://www.mbam.qc.ca/fr/education/prisme-la-boite-a-outils-numerique/

**Comment by ZoeRenaudie** [comment]
Date possible automne : 
- 17 septembre
- 3 dec
- 10 dec
Ou a l'hiver.

**Comment by ZoeRenaudie** [comment]
29 octobre! 11h30-12h30 
@emchateau tu lui proposes?

**Comment by emchateau** [comment]
Done.
Est-ce qu’il y a une raison particulière pour laquelle tu préférais que cela soit moi qui poursuive l’invitation ?

**Comment by ZoeRenaudie** [comment]
Elle t'avait demandé ce que tu en pensais, alors je me suis dis que tu voudrais lui répondre :)
