### ISSUE TITLE
Se documenter sur les plans de gestion des données

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#46]
Le projet doit établir un plan de gestion des données. Celui-ci doit être révisé chaque année.
- https://assistant.portagenetwork.ca
- https://www.ouvrirlascience.fr (voir le guide notamment)

**Comment by emchateau** [comment]
Le travail sur le plan de gestion des données devient urgent.
Nous devions l’établir la première année et le réévaluer chaque année. 
Mettre à l’ordre du jour d’une prochaine réunion.

**Comment by lenaMK** [comment]
plan initial et recherches sont dans le [drive](https://drive.google.com/drive/folders/1t4im7IFjxJ4Nu9eQ6Jzust0aQnthoSPu)
