### ISSUE TITLE
Rédiger les présentations des projets

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#50]
Format markdown, prévoir un template pour structurer l'information

**Comment by ktanton-work** [comment]
Projet
Mon programme de recherche consiste à développer des standards pour attacher, visualiser et partager des données pour des reconstitutions 3D de collections et d’expositions de musées historiques. La recherche ne porte pas seulement sur la documentation des modèles 3D, mais aussi sur la manière dont on peut partager les données entre de nombreux projets de recherche pour créer une ressource accessible à tous les axes du partenariat. Ce programme a le potentiel de créer des liens entre plusieurs études sur les collections de musées parmi tous les axes du projet partenariat.

Ce programme de recherche s’appuie sur mon expérience antérieure dans la reconstitution de monuments médiévaux disparus. Mon projet de reconstruction de modèles numériques est une base de données relationnelle externe qui renvoie à des modèles de reconstitution 3D créés dans des logiciels BIM/CAO. Il s’inscrit dans le cadre d’un projet plus vaste visant à développer des normes pour joindre, visualiser et partager les données des modèles 3D. Actuellement, il n’existe pas de normes pour joindre des informations externes à un modèle 3D. Pour joindre les décisions et les hypothèses prises pour créer une reconstitution 3D, j’ai développé un modèle de données qui identifie les principaux types de preuves utilisées pour les reconstitutions historiques : textuelles, lithiques, graphiques, archéologiques, comparatives et extrapolation hypothétique. La liaison des modèles 3D dans leur logiciel d’origine à une base de données permet une annotation des modèles afin qu’ils puissent être réutilisés par d’autres chercheuses et chercheurs après leur création initiale. 

Une partie significative de ce travail nécessite de développer une méthode de reconstitution et d’affichage qui clarifie la différence entre les preuves, les extrapolations basées sur ces preuves et les hypothèses pures. Pour que cela soit réalisable, j’intégrerai les pratiques architecturales existantes (par exemple, OpenBIM), qui me permettent de joindre des données à nos modèles. Ce travail intègre la technologie OpenBIM existante pour documenter toutes les données et le workflow du projet pour les modèles 3D, tout en répondant aux besoins uniques des reconstitutions historiques pour la communauté universitaire. Une partie importante du programme consistera à évaluer et à développer un processus d’annotation qui est logique pour les logiciels utilisés par les muséologues, tels que ArtSteps, Unity et Sketchfab.

L’objectif à long terme du programme de recherche est d’élaborer des normes pour l’annotation des projets de reconstitution 3D, qui comprennent la capture du workflow du projet ainsi que des données associées à la reconstitution historique. Enfin, le développement de normes de visualisation pour ces types de projets 3D doit être abordé, que les visualisations représentent des objets 3D — tels que les PDF 3D, la photogrammétrie, la réalité virtuelle, les vidéos et les vues IFC — ou des vues 2D (par exemple, des images fixes et des plans d’étage).

**Comment by ktanton-work** [comment]
Mes deux projets:

Le Inscribed Capitals Index (ICI) présente des exemples de chapiteaux avec des inscriptions lapidaires (ca.1080-1160) disponibles pour la recherche scientifique dans un format électronique consultable. La fiche individuelle de chaque chapiteau comprend une description du chapiteau, son emplacement indiqué sur un plan (lorsque cela est possible), ainsi que la transcription et la traduction de l'inscription. Les données sont présentées sous forme de tableaux, permettant aux utilisateurs de trier et de filtrer selon les catégories. L'ICI n'est pas un catalogue statique. Au contraire, la fonctionnalité du site permet des mises à jour et des extensions. Pour l'instant, l'ICI se concentre sur les capitales inscrites situées en France, mais il est prévu d'inclure à terme l'Espagne, l'Angleterre et l'Italie.


Le Digital Models Reconstruction project projet de reconstitution de modèles numériques est une base de données relationnelle externe, qui relie des modèles de reconstitution en 3D. Il s'agit essentiellement d'un moyen pour annoter (ou noter en bas de page) un modèle en 3D afin que le projet de modèle puisse être réutilisé par d'autres chercheurs après sa création initiale.

**Comment by lenaMK** [comment]
@emchateau ajouter CBC (et autres?)

**Comment by lenaMK** [comment]
je déplace ça dans les trucs à faire pour le site
