### ISSUE TITLE
Prendre connaissance des directives du FCI

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#59]
- [Guide des politiques et des programmes](https://www.innovation.ca/sites/default/files/file_uploads/guide_patch_2019_fr.pdf)
- [Modèle du rapport d’avancement de 
projet](https://www.innovation.ca/sites/default/files/file_uploads/guide_patch_2019_fr.pdf) Peut-être plus adapté, mais permet de se faire une idée.

**Comment by lenaMK** [comment]
Le lien pour le modèle du rapport d'avancement est erroné (c'est celui du guide)

**Comment by emchateau** [comment]
Voici le lien https://www.innovation.ca/fr/evaluer-rendement/faire-rapport-resultats
J’ai sollicité une rencontre avec les personnes responsables du FCI au Bureau de la recherche et de la valorisation BRDV. Ils me proposent mercredi à partir de 9H30, possible pour toi @lenaMK ?

**Comment by lenaMK** [comment]
oui c'est bon mercredi 9h30

**Comment by lenaMK** [comment]
rapport financier dû le 15 juin 2023, ajouté au calendrier général

**Comment by lenaMK** [comment]
tag `question` sur les annotations Hypothesis, par exemple je ne comprends pas comment s'applique la règle sur les rapports d'avancement pour nous  @emchateau

**Comment by emchateau** [comment]
Aucune idée. C’est peut-être seulement pour les projets de plus de 1M.
Nous poserons les questions à la réunion mercredi.
