### ISSUE TITLE
Courriel et nom de domaine

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#60]
Une demande a été faite pour la création du domaine ouvroir.umontreal.ca et l’ouverture d’une adresse courriel pour le laboratoire ouvroir@umontreal.ca

**Comment by lenaMK** [comment]
@emchateau  Est-ce que tu as eu des nouvelles du nom de domaine?

**Comment by emchateau** [comment]
Relance faite. Le message a été transmis au webmaster (18 janvier 2022) avec les indications nécessaires. Il reste à traiter la question du https
