### ISSUE TITLE
Envoyer les invitations au brown-bag lunches

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#69]

**Comment by lenaMK** [comment]
15 ou 22 mars, 5 ou 12 avril

**Comment by ktanton-work** [comment]
Robert peut nous retrouver pour un café à 10h30 le 15 mars (avant le midi-causerie). Je lui ai dit de me retrouver dans mon bureau et de partir de là. Nous devrons donc reprogrammer notre réunion hebdomadaire. Avons-nous un local pour le midi-causerie du 15 mars ?

**Comment by lenaMK** [comment]
Super pour le café avec Robert.
Oui, nous avons le local du CRIHN (c8132) de 11h à 13h.
Nous pouvons déplacer la réunion de labo à 9h le matin ou à 15h le même jour, sinon déplacer au jeudi matin par exemple?

**Comment by emchateau** [comment]
Il faut prévoir de faire circuler le courriel
- [ ] département histoire (peut-être moi ou Kristine en copie Ouvroir pour qu’ils prennent l’habitude de valider nos courriels)
- [ ] département histoire de l’art (peut-être moi ou Kristine en copie Ouvroir pour qu’ils prennent l’habitude de valider nos courriels)
- [ ] centre d’études médiévales (Kristine)
- [ ] CRIHN
- [ ] CIECO
- [ ] Collègues UQAM
- [ ] Collègues Concordia
- [ ] Collègues Laval

**Comment by lenaMK** [comment]
@ktanton-work pourrais-tu faire la diffusion auprès du centre d'études médiévales stp? et si tu as l'information de contact, au département d'histoire également?
Je vais transférer le courriel à Robert pour  qu'il puisse le diffuser de son côté

**Comment by ktanton-work** [comment]
Bonjour Lena,

J’ai partagé l’invitation au directeur du Centre d’études médiévales et le responsable de cycles supérieurs en histoire (Gordon Blenneman).

Woo-hoo—un bon départ !
Kristine

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d’histoire de l’art et d’études cinématographiques
514 343-2194

On Mar 9, 2022, at 9:46 AM, Lena Krause ***@***.******@***.***>> wrote:



@ktanton-work<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fktanton-work&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7Cda3d8160561340481eea08da01db957d%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637824339854356961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aYi8MtX7Wkn%2FwMvOuhorM0pBuZoJ8NeyrXselrLpV74%3D&reserved=0> pourrais-tu faire la diffusion auprès du centre d'études médiévales stp? et si tu as l'information de contact, au département d'histoire également?
Je vais transférer le courriel à Robert pour qu'il puisse le diffuser de son côté

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fouvroir%2Flabouvroir%2Fissues%2F69%23issuecomment-1062995895&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7Cda3d8160561340481eea08da01db957d%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637824339854356961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zHUdvadHQbuw4GItliOlxN6UPML6MDZRdp2UMYLErM0%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUCJHRUCYZCZQNQLPEI33CLU7C2T7ANCNFSM5MHZQK4Q&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7Cda3d8160561340481eea08da01db957d%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637824339854356961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KNsrnLNPVntomp2w6wVK9L1sOJXPIArNLPeeqg0%2B9QA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7Cda3d8160561340481eea08da01db957d%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637824339854512746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PRBzsmLCjw3w0zBVfvHxP0hHoOjOPQAy1L4P31fDE18%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7Cda3d8160561340481eea08da01db957d%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637824339854512746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZF%2FZrBQHwc5RB7vG%2Bn9jy6FPd%2FgvQZymLpwlncpm8Lw%3D&reserved=0>.

**Comment by lenaMK** [comment]
J'ai ajouté un billet (plutôt qu'un événement, pour faire plus simple, à propos du midi-causerie sur Mobilizon: https://mobilizon.fr/@ouvroir_lab
