### ISSUE TITLE
Configurer Git en ff-only

### ISSUE THREAD

**Issue by emchateau** [ouvroir/labouvroir#71]
Afin d’éviter les merge intempestifs, il faudrait que tu configures git sur ton ordi en pull.ff only au lieu de merge par défault.

```bash
git config --global pull.ff only
```

Git n’intégrera les modifications de la branche distance que si elles sont automatiquement réconciliables. Sinon il y aura un message d’erreur et tu pourras choisir la stratégie adaptée en fonction du cas de figure avec git merge ou git rebase ...

Comme il est possible que tu aies configuré individuellement les repo, si la commande de config globale ne fonctionne pas dans un repo après redémarrage du terminal, il faudrait exécuter la commande suivante dans chacun des dépôt

```bash
git config pull.ff only
```

Tu peux voir le statut du dépôt dans le `.git/config`

Cf. https://stackoverflow.com/questions/62653114/how-to-deal-with-this-git-warning-pulling-without-specifying-how-to-reconcile

**Comment by lenaMK** [comment]
c'est bon!
