### ISSUE TITLE
demander à INSO de réviser le rabais FCI pour les MacBook Pro

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#77]

**Comment by emchateau** [comment]
Je te confirme que les anciens prix et nouveaux prix / rabais sont bien dans le document budget_FCI en ligne. Pour te faire un recap:

en 2020, tu avais obtenu un devis pour 4 ordinateurs prix FCI de 6609.6 (soit 1650 l'unité), avec un rabais FCI de 1190$ ce qui représente 15.3% de rabais
le nouveau devis, 2002, offre pour 2 ordinateurs un prix FCI de 3786 (soit 1893 l'unité), avec un rabais FCI de 354$ ce qui représente 2.9% de rabais
ce sont ces chiffres qui sont entrées dans le budget FCI pour 2022, excepté que j'ai ajouté le coût du burin de normalisation à la ligne des ordinateurs (d'où le léger décalage par rapport aux chiffres ci-dessus pour 2022
en gros on veut le même rabais de 15%, comme ça on tombe confortablement dans le montant alloué (15% de rabais de 1893$ c'est 284$, donc un ordinateur reviendrait à 1609$)

**Comment by emchateau** [comment]
Done, négociation en cours.
