### ISSUE TITLE
Proposer une date en présentiel à Stephan Van Lieffering (CRIHN)

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#79]
Issu du crOuvroir2022-02-15: Lui proposer une date en présentiel à la fin de son semestre ou bien avoir une conférence en ligne.

**Comment by emchateau** [comment]
La date du 12 avril est confirmée. Il a cours en mâtinée. Prévoir une rencontre le 11 avril et le 13 avril.

**Comment by lenaMK** [comment]
le 11 ou le 13? @emchateau est-ce que c'est toi qui prévoit la rencontre avec lui?
