### ISSUE TITLE
Réfléchir au format des ateliers 2022-2023

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#85]
Options discutées pendant la réunion du 22 février: 

- 2h trop long? si c'est court mais régulier, ça pourrait augmenter la participation
- 2h minimum pour faire de la pratique? 
- séparer: atelier discussion-démonstration et atelier pratique? 
- démo autour d'un projet plus précis (pas juste un outil en général). éviter les présentations génériques? 
- présentations démos (invités) vs hands-on (plus long, organisé par l'ouvroir)

**Comment by lenaMK** [comment]
[Retours sur l'atelier 1](https://github.com/ouvroir/atelier1/blob/main/retours.md)

**Comment by emchateau** [comment]
Ce que je retiens de la discussion
- ne traiter que d’un sujet dans un temps court
- proposer un tutoriel avec un objectif bien identifié qui guidera l’atelier
- envisager à côté des ateliers des sessions démos

**Comment by ktanton-work** [comment]
C'est également mon souvenir.

Kristine Tanton
Professeure adjointe | Assistant Professor
Département d'histoire de l'art et d'études cinématographiques
514 343-2194

On Feb 23, 2022, at 4:00 PM, Emmanuel Château-Dutier ***@***.******@***.***>> wrote:



Ce que je retiens de la discussion

  *   ne traiter que d’un sujet dans un temps court
  *   proposer un tutoriel avec un objectif bien identifié qui guidera l’atelier
  *   envisager à côté des ateliers des sessions démos

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fouvroir%2Flabouvroir%2Fissues%2F85%23issuecomment-1049211686&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7C2f10d8e98c254cf0ca6d08d9f70f90ee%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637812468488617606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LjsMtvlTGwgpox6VCKD%2B8zRai2GnOVgFoIwCclDgeuE%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUCJHRVXUMIKH53YU2MQR33U4VDH7ANCNFSM5PE6LUHA&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7C2f10d8e98c254cf0ca6d08d9f70f90ee%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637812468488617606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kXEU6Ys3QGwq7zDuYqkXfvT86PKuSL7b2D8D4I%2B0238%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7C2f10d8e98c254cf0ca6d08d9f70f90ee%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637812468488617606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XYI%2Ff%2FdbuVPGi7GpP58UmOJlQHiT0aqW6twOAmtVt4U%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckristine.tanton%40umontreal.ca%7C2f10d8e98c254cf0ca6d08d9f70f90ee%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637812468488617606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CzOtP9yd4hu4fi%2BrV6LerLG0hDCLVl4UiaPODWCT16s%3D&reserved=0>.

**Comment by lenaMK** [comment]
proposition d'un atelier IIIF à l'automne lors d'une discussion sur common avec William et Emmanuel, avec les bibliothèques et les sciences, sur Atkins, faire un prototype d'expo ?

**Comment by ktanton-work** [comment]
Ça pourrait être bien pour un atelier. Qu'est-ce qu'Atkins ?

**Comment by emchateau** [comment]
Salut,
Atkins est une des premières photographes et c’est une femme. La réserve des livres rares de là bibliothèque conserve un magnifique recueil de cyanotypes réalisé par Atkins. Dans le cadre du don philanthropique de la fondation Courtois, notre université a numérisé le volume. Il s’agit de photographies d’algues. Il y aurait donc pantière à valoriser ce volume en faisant une exposition numérique avec des liens vers les espèces biologiques en utilisant des requêtes SPARQL.
Bien amicalement

Emmanuel Château
Professeur agrégé
Université de Montréal
@emchateau


Le 4 août 2022 à 18:26, ktanton-work ***@***.***> a écrit :

﻿

Ça pourrait être bien pour un atelier. Qu'est-ce qu'Atkins ?
