### ISSUE TITLE
Proposer une rencontre avec Josée et la coordinatrice à Michael pour parler du bureau partagé

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#95]

**Comment by emchateau** [comment]
Salut, c’est une question liée au local.
N’oublie pas non plus de mettre les issues dans le projet.

**Comment by lenaMK** [comment]
j'ai montré le local à Josée vendredi et nous avons discuté brièvement de l'organisation. Le·a coordinateur·rice du CRIHN commencera en juin
