### ISSUE TITLE
Répondre à CalculQc

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#98]
- demander à être informé aussitôt que le centre de données ETS-2 est de nouveau fonctionnel
 
Face aux réponses reçue, nous aimerions partir sur une offre cloud mais cela requiert d'organiser une embauche/prêt de service associée (c'est ce que j'ai retenu, je te laisse ajuster)

**Comment by lenaMK** [comment]
@emchateau il faut toujours répondre à Calcul Québec, pour faire le suivi comme convenu dans la [réunion Koumbit](https://demo.hedgedoc.org/NSJb8ZEhQ9yibmPHSaJhAQ#)

**Comment by lenaMK** [comment]
@emchateau si tu as le temps de répondre cette semaine?

**Comment by emchateau** [comment]
Aucune nouvelle de Koumbit, non plus.
En revanche, comme je te le disais Calcul Québec a réparé.
Par contre, ils sont toujours à la recherche du sysadmin

Emmanuel Château-Dutier
Professeur agrégé

**Comment by lenaMK** [comment]
@emchateau  au vu de la réponse de Koumbit, est-ce que ça te convient et si oui, est-ce que tu pourrais écrire à calcul québec pour s'assurer qu'on pourra donner des accès à Hubert et son équipe?

**Comment by lenaMK** [comment]
@emchateau j'avais noté que tu voulais contacter Suzanne Talon. Est-ce que je me charge de Koumbit et de prendre rdv avec Edna (si c'est nécessaire de prendre rdv avec elle?)

**Comment by emchateau** [comment]
Oui, il faut que je contacte Suzanne pour expliquer que l’on va sur la solution 20 000 au lieu de 30 000. Pour Edna, je pense qu’il faut l’informer de notre montage pour voir si elle est d’accord.

**Comment by emchateau** [comment]
et demander quelles sont les choses à faire au préalable avant d’engager quoi que ce soit.

**Comment by emchateau** [comment]
J'ai écris à Edna B pour obtenir la validation préalable du plan retenu.
Il faudra ensuite:
- Prendre contact avec Suzan Talon pour lui présenter notre scénario
- Valider avec Tim et mettre en route le travail
- Demander l’ouverture de la ressource à Calcul Québec (conformément aux suggestions que nous fera Tim)

**Comment by lenaMK** [comment]
@emchateau as-tu pu contacter Suzanne Talon? 
Si ce n'est pas encore fait, peux-tu mettre l'ouvroir en cc quand tu l'envoies? Merci

**Comment by emchateau** [comment]
Je viens de le faire
